import { ShopOfferKind } from '@/types/shop-offer';
import { ShopStockPeriod, type ShopStockCatalogEntry } from '@/types/shop-stock';

export const SHOP_STOCK_CATALOG: ShopStockCatalogEntry[] = [
  // ——— Estoque diário · moedas ———
  {
    id: 'daily_coins_shield',
    period: ShopStockPeriod.DAILY,
    shopKind: ShopOfferKind.COINS,
    productKey: 'shield_1',
    maxStock: 5,
    title: 'Bancada do ferreiro',
    story: 'O ferreiro trouxe poucos escudos hoje — quando acabar, só amanhã.',
    merchantName: 'Ferreiro Matinal',
    merchantEmoji: '🔨',
    weight: 10,
  },
  {
    id: 'daily_coins_duo',
    period: ShopStockPeriod.DAILY,
    shopKind: ShopOfferKind.COINS,
    productKey: 'shield_duo',
    maxStock: 3,
    title: 'Par reservado',
    story: 'Dois escudos embrulhados à pressa para quem chegou cedo à loja.',
    merchantName: 'Aprendiz da Forja',
    merchantEmoji: '🛡️',
    weight: 8,
  },
  {
    id: 'daily_coins_common_box',
    period: ShopStockPeriod.DAILY,
    shopKind: ShopOfferKind.COINS,
    productKey: 'loot_box_common',
    maxStock: 4,
    title: 'Caixas da manhã',
    story: 'Lote pequeno de caixas comuns — a entrega do dia é limitada.',
    merchantName: 'Entregador da Praça',
    merchantEmoji: '📦',
    weight: 9,
  },
  {
    id: 'daily_coins_uncommon_box',
    period: ShopStockPeriod.DAILY,
    shopKind: ShopOfferKind.COINS,
    productKey: 'loot_box_uncommon',
    maxStock: 3,
    title: 'Prateleira incomum',
    story: 'Só couberam três caixas incomuns no balcão. Quem dorme, perde.',
    merchantName: 'Estoquista da Loja',
    merchantEmoji: '🌿',
    weight: 7,
  },
  {
    id: 'daily_coins_cafe',
    period: ShopStockPeriod.DAILY,
    shopKind: ShopOfferKind.COINS,
    productKey: 'cafe_expresso_coin',
    maxStock: 6,
    title: 'Cantinho do café',
    story: 'Café fresco para estudantes — estoque do dia, sem reposição.',
    merchantName: 'Barista da Esquina',
    merchantEmoji: '☕',
    weight: 8,
  },
  {
    id: 'daily_coins_xp',
    period: ShopStockPeriod.DAILY,
    shopKind: ShopOfferKind.COINS,
    productKey: 'xp_potion_coin',
    maxStock: 4,
    title: 'Frascos do laboratório',
    story: 'O alquimista preparou poucos soros hoje. Amanhã ele tenta de novo.',
    merchantName: 'Alquimista Local',
    merchantEmoji: '🧪',
    weight: 7,
  },
  {
    id: 'daily_coins_ticket',
    period: ShopStockPeriod.DAILY,
    shopKind: ShopOfferKind.COINS,
    productKey: 'free_loot_ticket_coin',
    maxStock: 3,
    title: 'Tickets do dia',
    story: 'Bilhetes de loot impressos esta manhã — quantidade limitada na vitrine.',
    merchantName: 'Impressor da Guilda',
    merchantEmoji: '🎁',
    weight: 6,
  },

  // ——— Estoque diário · SP ———
  {
    id: 'daily_sp_common',
    period: ShopStockPeriod.DAILY,
    shopKind: ShopOfferKind.STUDY_POINTS,
    productKey: 'box_common',
    maxStock: 5,
    title: 'Bolsa da manhã',
    story: 'Study Points renderam um lote pequeno de caixas comuns. Estoque contado.',
    merchantName: 'Tesoureira SP',
    merchantEmoji: '⚡',
    weight: 10,
  },
  {
    id: 'daily_sp_uncommon',
    period: ShopStockPeriod.DAILY,
    shopKind: ShopOfferKind.STUDY_POINTS,
    productKey: 'box_uncommon',
    maxStock: 3,
    title: 'Reserva incomum',
    story: 'Três caixas incomuns separadas para quem farmou SP com disciplina.',
    merchantName: 'Curadora SP',
    merchantEmoji: '📦',
    weight: 8,
  },
  {
    id: 'daily_sp_booster',
    period: ShopStockPeriod.DAILY,
    shopKind: ShopOfferKind.STUDY_POINTS,
    productKey: 'booster_study',
    maxStock: 4,
    title: 'Boosters frescos',
    story: 'Boosters recém-destilados — perdem potência se ninguém comprar hoje.',
    merchantName: 'Destilador de Foco',
    merchantEmoji: '⚡',
    weight: 9,
  },
  {
    id: 'daily_sp_ticket',
    period: ShopStockPeriod.DAILY,
    shopKind: ShopOfferKind.STUDY_POINTS,
    productKey: 'free_loot_ticket',
    maxStock: 3,
    title: 'Tickets reservados',
    story: 'A guilda SP liberou poucos tickets. A fila é virtual, o estoque é real.',
    merchantName: 'Mensageiro SP',
    merchantEmoji: '🎫',
    weight: 7,
  },
  {
    id: 'daily_sp_kit',
    period: ShopStockPeriod.DAILY,
    shopKind: ShopOfferKind.STUDY_POINTS,
    productKey: 'kit_escudo',
    maxStock: 4,
    title: 'Kits de emergência',
    story: 'Kits de escudo para dias difíceis — estoque mínimo, renovação diária.',
    merchantName: 'Guarda da Biblioteca',
    merchantEmoji: '🧰',
    weight: 8,
  },
  {
    id: 'daily_sp_xp',
    period: ShopStockPeriod.DAILY,
    shopKind: ShopOfferKind.STUDY_POINTS,
    productKey: 'xp_potion_small',
    maxStock: 5,
    title: 'Soros do turno',
    story: 'Frascos preparados no turno da manhã. À noite, a prateleira fecha vazia.',
    merchantName: 'Química da Academia',
    merchantEmoji: '🧪',
    weight: 7,
  },

  // ——— Estoque semanal · moedas ———
  {
    id: 'weekly_coins_mega',
    period: ShopStockPeriod.WEEKLY,
    shopKind: ShopOfferKind.COINS,
    productKey: 'shield_mega_pack',
    maxStock: 2,
    title: 'Cofre semanal de escudos',
    story: 'Uma vez por semana o cofre municipal abre cinco escudos. Poucas unidades.',
    merchantName: 'Tesoureiro Semanal',
    merchantEmoji: '🏛️',
    weight: 6,
  },
  {
    id: 'weekly_coins_rare',
    period: ShopStockPeriod.WEEKLY,
    shopKind: ShopOfferKind.COINS,
    productKey: 'loot_box_rare',
    maxStock: 2,
    title: 'Remessa rara',
    story: 'Navio semanal atracou com caixas raras. Descarregamento lento, estoque curto.',
    merchantName: 'Capitão Semanal',
    merchantEmoji: '⚓',
    weight: 7,
  },
  {
    id: 'weekly_coins_epic',
    period: ShopStockPeriod.WEEKLY,
    shopKind: ShopOfferKind.COINS,
    productKey: 'loot_box_epic',
    maxStock: 1,
    title: 'Relíquia da semana',
    story: 'Uma única caixa épica por semana — tradição antiga da guilda mercante.',
    merchantName: 'Guilda Mercante',
    merchantEmoji: '🐉',
    weight: 4,
  },
  {
    id: 'weekly_coins_golden',
    period: ShopStockPeriod.WEEKLY,
    shopKind: ShopOfferKind.COINS,
    productKey: 'golden_ticket_coin',
    maxStock: 2,
    title: 'Tickets dourados',
    story: 'Tickets impressos na segunda-feira. Quando acabam, espera até a próxima.',
    merchantName: 'Cunharia Real',
    merchantEmoji: '🎫',
    weight: 5,
  },
  {
    id: 'weekly_coins_booster',
    period: ShopStockPeriod.WEEKLY,
    shopKind: ShopOfferKind.COINS,
    productKey: 'booster_study_coin',
    maxStock: 2,
    title: 'Lote de boosters',
    story: 'Boosters concentrados chegam uma vez por semana. Potência máxima, quantidade mínima.',
    merchantName: 'Laboratório Central',
    merchantEmoji: '⚡',
    weight: 5,
  },

  // ——— Estoque semanal · SP ———
  {
    id: 'weekly_sp_rare',
    period: ShopStockPeriod.WEEKLY,
    shopKind: ShopOfferKind.STUDY_POINTS,
    productKey: 'box_rare',
    maxStock: 2,
    title: 'Leilão raro',
    story: 'Caixas raras entram no leilão SP toda segunda. Poucos lances, poucas unidades.',
    merchantName: 'Leiloeiro SP',
    merchantEmoji: '💎',
    weight: 7,
  },
  {
    id: 'weekly_sp_epic',
    period: ShopStockPeriod.WEEKLY,
    shopKind: ShopOfferKind.STUDY_POINTS,
    productKey: 'box_epic',
    maxStock: 1,
    title: 'Épica da semana',
    story: 'Uma caixa épica coroa o estoque semanal. Quem compra, conta história até a próxima segunda.',
    merchantName: 'Curador Épico',
    merchantEmoji: '🌟',
    weight: 4,
  },
  {
    id: 'weekly_sp_legendary',
    period: ShopStockPeriod.WEEKLY,
    shopKind: ShopOfferKind.STUDY_POINTS,
    productKey: 'box_legendary',
    maxStock: 1,
    title: 'Lendária singular',
    story: 'Só uma caixa lendária por semana na loja SP. Os veteranos já sabem o horário.',
    merchantName: 'Mestre Lendário',
    merchantEmoji: '👑',
    weight: 3,
  },
  {
    id: 'weekly_sp_collector',
    period: ShopStockPeriod.WEEKLY,
    shopKind: ShopOfferKind.STUDY_POINTS,
    productKey: 'legendary_collector',
    maxStock: 2,
    title: 'Ímã do colecionador',
    story: 'Ímãs lendários reabastecem semanalmente. Sorte boa não espera.',
    merchantName: 'Colecionador Mestre',
    merchantEmoji: '🧲',
    weight: 5,
  },
  {
    id: 'weekly_sp_double_xp',
    period: ShopStockPeriod.WEEKLY,
    shopKind: ShopOfferKind.STUDY_POINTS,
    productKey: 'double_xp_1h',
    maxStock: 2,
    title: 'Elixir semanal',
    story: 'Elixir de XP em dobro — frascos raros, reposição só na segunda-feira.',
    merchantName: 'Alquimista Chefe',
    merchantEmoji: '✨',
    weight: 4,
  },
  {
    id: 'weekly_sp_egg',
    period: ShopStockPeriod.WEEKLY,
    shopKind: ShopOfferKind.STUDY_POINTS,
    productKey: 'pet_egg',
    maxStock: 1,
    title: 'Ovo da semana',
    story: 'Um ovo de pet por semana. A fazenda só envia um — quem perde, aguarda o próximo ciclo.',
    merchantName: 'Fazendeiro Viajante',
    merchantEmoji: '🥚',
    weight: 2,
  },
];

export const SHOP_STOCK_CATALOG_BY_ID = Object.fromEntries(
  SHOP_STOCK_CATALOG.map((entry) => [entry.id, entry]),
) as Record<string, ShopStockCatalogEntry>;

export const SHOP_STOCK_MESSAGES = {
  purchaseCompleted: 'Compra do estoque concluída!',
  itemReceived: 'Item adicionado ao seu inventário.',
  outOfStock: 'Esgotado — aguarde a próxima reposição.',
  insufficientCoins: 'Moedas insuficientes.',
  insufficientSp: 'Study Points insuficientes.',
  unavailable: 'Este item não está mais no estoque.',
  purchaseCanceled: 'Compra cancelada.',
} as const;
