export const CITY_UI = {
  screenTitle: 'Cidade Viva',
  screenSubtitle: 'Explore o mapa, visite locais e acompanhe sua expansão.',
  tabMap: 'Mapa',
  tabSummary: 'Resumo',
  mapVitalityLabel: 'Vitalidade',
  mapPlacesUnlocked: (unlocked: number, total: number) =>
    `${unlocked} de ${total} locais desbloqueados`,
  mapDistrictsActive: (active: number, total: number) =>
    `${active}/${total} distritos ativos`,
  mapLegend: (active: number, total: number) =>
    `7×6 quarteirões · ${active}/${total} distritos · bordas tracejadas`,
  mapCanvasLabel: 'Mapa da cidade com locais clicáveis',
  mapHint: 'Toque em um local para missões e contratos. O pin pulsante indica o emissor do contrato ativo.',
  mapHintGmaps:
    'Arraste para explorar · use +/− para zoom · toque no marcador para abrir o local.',
  mapEmptyPois: 'Nenhum local no mapa. Reinicie o app para sincronizar a cidade.',
  poiModalClose: 'Fechar local',
  poiModalDistrict: (name: string) => `Distrito · ${name}`,
  poiModalLevelLabel: 'Nível do local',
  poiModalNpcQuote: 'NPC',
  poiOverviewDefaultHint:
    'Use as abas Missões e Contratos para progredir neste local. Locais com obra aceitam entregas na aba Entregar.',
  libraryArenaHint:
    'A biblioteca e o coliseu concedem +1 stamina de duelo uma vez por dia ao abrir a Arena.',
  poiNpcLabel: 'NPC do local',
  poiCategoryLabel: (category: string) => {
    const labels: Record<string, string> = {
      civic: 'Cívico',
      education: 'Educação',
      commerce: 'Comércio',
      work: 'Trabalho',
      culture: 'Cultura',
      travel: 'Viagem',
      social: 'Social',
    };
    return labels[category] ?? category;
  },
  poiLocalLevelTitle: 'Nível do local',
  poiLevelStars: (level: number, max: number) =>
    `${'⭐'.repeat(level)}${'☆'.repeat(Math.max(0, max - level))}`,
  poiMaxLevel: 'Nível máximo',
  poiXpRemaining: (xp: number) => `${xp} XP para subir`,
  poiXpProgress: (current: number, percent: number) =>
    `${current} XP local · ${percent}% até o próximo nível`,
  poiMissionsTitle: 'Missões do local',
  poiMissionsHint: 'O progresso atualiza ao estudar, focar ou cumprir metas. Resgate quando concluir.',
  poiMissionsEmpty: 'Nenhuma missão hoje — volte amanhã.',
  poiChainsTitle: 'História do local',
  poiChainsHint:
    'Missões em sequência com o NPC. Conclua um passo para liberar o próximo — progresso salvo entre dias.',
  poiChainStepProgress: (current: number, total: number) => `Passo ${current} de ${total}`,
  poiChainComplete: 'Arco concluído',
  poiChainArchived: 'Você completou esta história. O NPC lembra de você.',
  poiContractsTitle: 'Contratos do local',
  poiContractsHint:
    'Desafios emitidos por este NPC. Um contrato ativo por vez; concluir concede XP local ao emissor.',
  poiContractsEmpty: 'Nenhum contrato disponível aqui — suba o nível do local ou do jogador.',
  poiContractActiveElsewhere: (contractName: string, poiName: string) =>
    `«${contractName}» está ativo em ${poiName}. Vá até lá para acompanhar.`,
  poiDeliverTitle: 'Entregar recursos',
  poiDeliverHint:
    'Palavras do farm viram tijolos automaticamente. Entregue aqui para avançar a obra do local.',
  poiDeliverNotAvailable: 'Este local ainda não aceita entregas de recursos.',
  poiDeliverNoProject: 'Nenhuma obra ativa esta semana.',
  poiDeliverRequestLabel: 'Pedido da semana',
  poiDeliverRequest: (emoji: string, label: string, total: number) =>
    `${emoji} ${total} ${label}`,
  poiDeliverProgress: 'Obra em andamento',
  poiDeliverProgressPercent: (percent: number) => `${percent}% concluído`,
  poiDeliverYouHave: (amount: number, emoji: string) => `Você tem ${amount} ${emoji}`,
  poiDeliverChunk: (chunk: number) => `Entrega por lote: ${chunk}`,
  poiDeliverDailyCapHint: (cap: number) => `Limite diário de entrega: ${cap}`,
  poiDeliverButton: (chunk: number) => `Entregar ${chunk}`,
  poiDeliverComplete: 'Obra da semana concluída — volte na próxima segunda.',
  poiDeliverInsufficient: 'Recursos insuficientes no estoque da cidade.',
  poiDeliverDailyCapReached: 'Limite diário de entrega atingido para este recurso.',
  poiDeliverFailed: 'Não foi possível entregar agora.',
  poiDeliverSuccess: (amount: number) => `Entregue ${amount} — a obra avançou.`,
  poiDeliverSuccessComplete: (amount: number, localXp: number) =>
    `Obra concluída! +${amount} entregues e +${localXp} XP local ao local.`,
  memoryWallTitle: 'Muro da memória',
  memoryWallHint:
    'Cada palavra do farm vira um tijolo. Coloque na planta da obra — moedas não substituem tijolos temáticos.',
  memoryWallSlotRow: (filled: number, target: number, label: string) =>
    `${filled}/${target} · ${label}`,
  memoryWallSlotNeed: (remaining: number, themeTag: string) =>
    `Faltam ${remaining} tijolos de ${themeTag} para a estante.`,
  memoryWallInventory: (solid: number, cracked: number) =>
    `${solid} tijolos prontos · ${cracked} rachados`,
  memoryWallPlaceButton: (chunk: number) => `Colocar tijolos (${chunk})`,
  memoryWallRepairButton: (count: number) => `Reparar ${count} rachado${count === 1 ? '' : 's'}`,
  memoryWallPlaceSuccess: (n: number) => `${n} tijolo${n === 1 ? '' : 's'} assentado${n === 1 ? '' : 's'} no muro.`,
  memoryWallPlaceComplete: (localXp: number) =>
    `A ala abriu! +${localXp} XP local — novas missões na biblioteca.`,
  memoryWallNoBricks: 'Nenhum tijolo compatível no estoque. Estude no farm no tema certo.',
  memoryWallDailyCap: 'Limite diário de colocações atingido.',
  memoryWallCrackedHint: 'Esta palavra enfraqueceu — repare o muro (30s).',
  memoryWallRepairTitle: 'Reparar muro',
  memoryWallRepairPrompt: (lemma: string) => `Qual é a palavra em inglês para «${lemma}»?`,
  memoryWallRepairWrong: 'Ainda rachado — tente de novo.',
  memoryWallRepairSuccess: (lemma: string) => `«${lemma}» voltou ao muro.`,
  mapResourcesLabel: 'Estoque da cidade',
  cityRumorLabel: 'Rumor na cidade',
  eventBannerDaysLeft: (days: number) =>
    days === 1 ? '1 dia restante' : `${days} dias restantes`,
  eventBannerSpirit: (spirit: number, label: string) => `${label}: ${spirit}%`,
  eventBannerVocab: (learned: number, target: number, emoji: string) =>
    `${emoji} ${learned}/${target} palavras do evento`,
  eventIntroCta: 'Explorar o mapa',
  eventMissionsTitle: (eventName: string) => `Missões · ${eventName}`,
  eventMissionsHint: 'Válidas enquanto o evento estiver ativo. Vocabulário conta no farm.',
  eventContractsTitle: (eventName: string) => `Contratos · ${eventName}`,
  eventSpiritMilestones: 'Marcos do espírito',
  eventMilestoneReached: (value: number) => `Marco ${value}% alcançado`,
  vitalityHigh: 'Cidade vibrante',
  vitalityMid: 'Cidade estável',
  vitalityLow: 'Cidade precisa de você',
  parkPetTitle: 'Pet no parque',
  parkPetHint: 'Traga seu pet para ganhar felicidade extra. Vitalidade alta deixa o passeio ainda melhor.',
  parkPetButton: 'Levar pet ao parque',
  parkPetSuccess: 'Seu pet adorou o passeio! +felicidade.',
  parkPetAlready: 'Seu pet já passeou aqui hoje.',
  parkPetFailed: 'Não foi possível levar o pet agora.',
  parkPetNoPet: 'Adote um pet no app para usar o parque.',
  museumTitle: 'Museu da Temporada',
  museumHint: 'Exposição do seu progresso no season pass deste mês.',
  museumSeasonPoints: 'Pontos da temporada',
  museumTiersClaimed: 'Tiers resgatados',
  museumFooter: 'Continue cumprindo missões e contratos para encher a vitrine.',
  npcFlavorDefault: (npcName: string) => `${npcName} te cumprimenta calorosamente.`,
  poiLockedTitle: 'Local bloqueado',
  poiLockedBody: (level: number) =>
    `Desbloqueie este local ao atingir o nível ${level} e avançar no distrito.`,
  heroTitle: 'Cidade Internacional',
  heroSubtitle: 'Cada nível que você sobe adiciona um novo marco à sua metrópole global.',
  howItWorksTitle: 'Como funciona',
  howItWorksSteps: [
    'Ganhe XP com missões, estudos e modo foco.',
    'Ao atingir o nível exigido, a construção é liberada automaticamente.',
    'Alguns marcos concedem títulos exclusivos no seu perfil.',
  ] as const,
  statsBuiltLabel: 'Marcos construídos',
  statsCityLabel: 'Expansão',
  statsNextLabel: 'Até o próximo marco',
  skylineBuilt: (unlocked: number, total: number) => `${unlocked} de ${total} construídos`,
  skylineTitle: 'Horizonte',
  skylineSubtitle: 'Deslize para ver todos os marcos — coloridos já foram conquistados.',
  roadmapTitle: 'Rota de expansão',
  roadmapSubtitle: 'Marcos principais da sua jornada internacional.',
  districtsTitle: 'Distritos avançados',
  districtsSubtitle: 'Regiões extras desbloqueadas a partir do nível 30.',
  districtsMore: (count: number) => `+${count} distritos ainda no horizonte`,
  statusActive: 'Atual',
  statusBuilt: 'Construído',
  statusLocked: 'Bloqueado',
  levelsRemaining: (n: number) => (n === 1 ? 'Falta 1 nível' : `Faltam ${n} níveis`),
  vibrancyWarning: 'A cidade está menos vibrante — volte a estudar para recuperar a energia.',
} as const;
