export const PET_UI = {
  screenTitle: 'Meu Companheiro',
  screenSubtitle: 'Cuide, evolua e colecione memórias',
  labTitle: 'Laboratório de Incubação',
  labSubtitle: 'Ambiente controlado até a eclosão',
  labBadge: 'LAB-07 · Incubadora',
  labStatusStable: 'Ambiente estável',
  labSpeciesLabel: 'Espécime em análise',
  labCountdownLabel: 'Eclosão estimada',
  labProgressLabel: 'Progresso da incubação',
  labStudyHint:
    'Continue estudando no app — o XP ajuda seu companheiro a evoluir mais rápido após a eclosão.',
  labEvolutionHint: 'Estude e ganhe XP para evoluir do ovo (nível 5) mais cedo.',
  labMetricTemp: 'Temperatura',
  labMetricTempValue: '37.0°C',
  labMetricHumidity: 'Umidade',
  labMetricHumidityValue: 'Ótima',
  labMetricEnergy: 'Núcleo',
  labMetricEnergyValue: 'Estável',
  labHatchSoon: 'Eclosão em breve…',
  labDialogue:
    'Estou confortável aqui. Quando o timer zerar, finalmente poderei sair desta cápsula!',
  farmCta: 'Fazenda de Pets',
  farmCtaHint: 'Pasto, cruzamento e glossário',
} as const;
