import type { PetIconRef } from '@/types/pet-instance';

/** Fallback vetorial quando a espécie não tem emoji no catálogo. UI principal usa `species.emoji`. */
export const PET_SPECIES_ICONS: Record<string, PetIconRef> = {
  codeowl: { library: 'MaterialCommunityIcons', name: 'owl' },
  quantumowl: { library: 'MaterialCommunityIcons', name: 'owl' },
  openowl: { library: 'MaterialCommunityIcons', name: 'owl' },
  debugduck: { library: 'MaterialCommunityIcons', name: 'duck' },
  gitcat: { library: 'MaterialCommunityIcons', name: 'cat' },
  bytebunny: { library: 'MaterialCommunityIcons', name: 'rabbit' },
  stackfox: { library: 'MaterialCommunityIcons', name: 'fox' },
  loopfrog: { library: 'MaterialCommunityIcons', name: 'frog' },
  cachebear: { library: 'MaterialCommunityIcons', name: 'bear' },
  blockchainbear: { library: 'MaterialCommunityIcons', name: 'polar-bear' },
  pingpanda: { library: 'MaterialCommunityIcons', name: 'panda' },
  mergepenguin: { library: 'MaterialCommunityIcons', name: 'penguin' },
  deploydragon: { library: 'MaterialCommunityIcons', name: 'snake' },
  cloudkoala: { library: 'MaterialCommunityIcons', name: 'koala' },
  apishark: { library: 'MaterialCommunityIcons', name: 'shark' },
  reactraptor: { library: 'MaterialCommunityIcons', name: 'dinosaur' },
  nodeunicorn: { library: 'MaterialCommunityIcons', name: 'horse' },
  sqlsnake: { library: 'MaterialCommunityIcons', name: 'snake' },
  vimviper: { library: 'MaterialCommunityIcons', name: 'snake' },
  devdolphin: { library: 'MaterialCommunityIcons', name: 'dolphin' },
  bugbee: { library: 'MaterialCommunityIcons', name: 'bee' },
  scal_eagle: { library: 'MaterialCommunityIcons', name: 'bird' },
  globalhawk: { library: 'MaterialCommunityIcons', name: 'bird' },
  kernelkraken: { library: 'MaterialCommunityIcons', name: 'octopus' },
  asyncphoenix: { library: 'Lucide', name: 'Bird' },
  passportphoenix: { library: 'Lucide', name: 'Bird' },
  aiphoenix: { library: 'Lucide', name: 'Bird' },
  remotegriffin: { library: 'MaterialCommunityIcons', name: 'lion' },
  legendarylion: { library: 'MaterialCommunityIcons', name: 'lion' },
  fullstacktiger: { library: 'MaterialCommunityIcons', name: 'lion' },
  microservicewolf: { library: 'MaterialCommunityIcons', name: 'wolf' },
  celestialwhale: { library: 'MaterialCommunityIcons', name: 'whale' },
  worldserpent: { library: 'MaterialCommunityIcons', name: 'snake' },
  rustcrab: { library: 'MaterialCommunityIcons', name: 'crab' },
  dockerdog: { library: 'MaterialCommunityIcons', name: 'dog' },
  lambdaotter: { library: 'MaterialCommunityIcons', name: 'otter' },
  graphqlama: { library: 'MaterialCommunityIcons', name: 'llama' },
  typescripturtle: { library: 'MaterialCommunityIcons', name: 'turtle' },
  terraformtortoise: { library: 'MaterialCommunityIcons', name: 'turtle' },
  kubchick: { library: 'MaterialCommunityIcons', name: 'bird' },
  redisram: { library: 'MaterialCommunityIcons', name: 'sheep' },
  elasticelk: { library: 'MaterialCommunityIcons', name: 'deer' },
  agilegecko: { library: 'MaterialCommunityIcons', name: 'snake' },
  owlyote: { library: 'MaterialCommunityIcons', name: 'wolf' },
  ducktor: { library: 'MaterialCommunityIcons', name: 'duck' },
  catshark: { library: 'MaterialCommunityIcons', name: 'shark' },
  raptoracle: { library: 'MaterialCommunityIcons', name: 'dinosaur' },
  phoenixbee: { library: 'MaterialCommunityIcons', name: 'bee' },
  griffwhale: { library: 'MaterialCommunityIcons', name: 'whale' },
  quantumserpent: { library: 'MaterialCommunityIcons', name: 'snake' },
  fullstackling: { library: 'MaterialCommunityIcons', name: 'penguin' },
};

export const getSpeciesIcon = (speciesKey: string): PetIconRef =>
  PET_SPECIES_ICONS[speciesKey] ?? { library: 'MaterialCommunityIcons', name: 'paw' };
