import { routes } from '@/constants'
import { FarmActivityType } from '@/types/farm'
import { LearningWorldKey, type LearningCurriculumUnitDefinition } from '@/types/learning-gps'

export const DEVELOPER_CURRICULUM_UNITS: LearningCurriculumUnitDefinition[] = [
  {
    key: 'developer_programming',
    worldKey: LearningWorldKey.DEVELOPER,
    kind: 'vocabulary',
    title: 'Programação',
    emoji: '⌨️',
    description: 'Código, linguagens, bugs e fluxo de desenvolvimento.',
    practiceRoute: routes.farm,
    practiceLabel: 'Praticar no Farm',
    practiceActivity: FarmActivityType.PROGRAMMING,
    requiredPracticeAmount: 8,
    sortOrder: 1,
  },
  {
    key: 'developer_frontend_backend',
    worldKey: LearningWorldKey.DEVELOPER,
    kind: 'vocabulary',
    title: 'Frontend & Backend',
    emoji: '🖥️',
    description: 'UI, APIs, servidores e arquitetura de aplicações.',
    practiceRoute: routes.farm,
    practiceLabel: 'Aprender termos',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 8,
    sortOrder: 2,
  },
  {
    key: 'developer_cloud_apis',
    worldKey: LearningWorldKey.DEVELOPER,
    kind: 'vocabulary',
    title: 'Cloud & APIs',
    emoji: '☁️',
    description: 'Deploy, containers, endpoints e integrações.',
    practiceRoute: routes.flashDeckReview,
    practiceLabel: 'Revisar vocabulário',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 6,
    sortOrder: 3,
  },
  {
    key: 'developer_architecture',
    worldKey: LearningWorldKey.DEVELOPER,
    kind: 'vocabulary',
    title: 'Arquitetura & DevOps',
    emoji: '🏗️',
    description: 'Pipelines, CI/CD, escalabilidade e monitoramento.',
    practiceRoute: routes.farm,
    practiceLabel: 'Praticar no Farm',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 6,
    sortOrder: 4,
  },
  {
    key: 'developer_grammar_b2',
    worldKey: LearningWorldKey.DEVELOPER,
    kind: 'grammar',
    title: 'Gramática técnica B2',
    emoji: '📐',
    description: 'Tempos verbais e estruturas em contexto profissional.',
    practiceRoute: routes.duels,
    practiceLabel: 'Duelo B2',
    practiceActivity: FarmActivityType.EXERCISE,
    requiredPracticeAmount: 4,
    sortOrder: 5,
  },
  {
    key: 'developer_reading_docs',
    worldKey: LearningWorldKey.DEVELOPER,
    kind: 'vocabulary',
    title: 'Reading: documentação',
    emoji: '📖',
    description: 'Leia documentações reais de frameworks e APIs.',
    practiceRoute: routes.farm,
    practiceLabel: 'Ler no Farm',
    practiceActivity: FarmActivityType.READING,
    requiredPracticeAmount: 4,
    sortOrder: 6,
  },
  {
    key: 'developer_listening_podcasts',
    worldKey: LearningWorldKey.DEVELOPER,
    kind: 'vocabulary',
    title: 'Listening: podcasts tech',
    emoji: '🎙️',
    description: 'Compreenda podcasts de tecnologia em inglês.',
    practiceRoute: routes.farm,
    practiceLabel: 'Ouvir no Farm',
    practiceActivity: FarmActivityType.LISTENING,
    requiredPracticeAmount: 3,
    sortOrder: 7,
  },
  {
    key: 'developer_writing_messages',
    worldKey: LearningWorldKey.DEVELOPER,
    kind: 'vocabulary',
    title: 'Writing: mensagens profissionais',
    emoji: '✉️',
    description: 'E-mails, PRs e mensagens para equipes internacionais.',
    practiceRoute: routes.farm,
    practiceLabel: 'Escrever no Farm',
    practiceActivity: FarmActivityType.READING,
    requiredPracticeAmount: 3,
    sortOrder: 8,
  },
  {
    key: 'developer_speaking_projects',
    worldKey: LearningWorldKey.DEVELOPER,
    kind: 'speaking',
    title: 'Speaking: explicar projetos',
    emoji: '🗣️',
    description: 'Apresente arquitetura, decisões técnicas e trade-offs.',
    practiceRoute: routes.farm,
    practiceLabel: 'Conversação no Farm',
    practiceActivity: FarmActivityType.SPEAKING,
    requiredPracticeAmount: 4,
    sortOrder: 9,
  },
  {
    key: 'developer_checkpoint_international',
    worldKey: LearningWorldKey.DEVELOPER,
    kind: 'checkpoint',
    title: 'Checkpoint: ambiente internacional',
    emoji: '🏁',
    description: 'Simule um dia de trabalho em equipe global em inglês.',
    practiceRoute: routes.farm,
    practiceLabel: 'Praticar speaking',
    practiceActivity: FarmActivityType.SPEAKING,
    requiredPracticeAmount: 6,
    sortOrder: 10,
  },
]
