import { routes } from '@/constants'
import { FarmActivityType } from '@/types/farm'
import { LearningWorldKey, type LearningCurriculumUnitDefinition } from '@/types/learning-gps'

export const EXPLORER_CURRICULUM_UNITS: LearningCurriculumUnitDefinition[] = [
  {
    key: 'explorer_travel',
    worldKey: LearningWorldKey.EXPLORER,
    kind: 'vocabulary',
    title: 'Viagens',
    emoji: '✈️',
    description: 'Aeroporto, passaporte, destinos e frases de viagem.',
    practiceRoute: routes.farm,
    practiceLabel: 'Praticar no Farm',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 8,
    sortOrder: 1,
  },
  {
    key: 'explorer_transport',
    worldKey: LearningWorldKey.EXPLORER,
    kind: 'vocabulary',
    title: 'Transporte',
    emoji: '🚌',
    description: 'Ônibus, metrô, táxi e pedir direções.',
    practiceRoute: routes.flashDeckReview,
    practiceLabel: 'Revisar vocabulário',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 6,
    sortOrder: 2,
  },
  {
    key: 'explorer_shopping',
    worldKey: LearningWorldKey.EXPLORER,
    kind: 'vocabulary',
    title: 'Compras',
    emoji: '🛍️',
    description: 'Lojas, preços, tamanhos e pagamento.',
    practiceRoute: routes.farm,
    practiceLabel: 'Aprender palavras',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 8,
    sortOrder: 3,
  },
  {
    key: 'explorer_restaurant',
    worldKey: LearningWorldKey.EXPLORER,
    kind: 'vocabulary',
    title: 'Restaurantes',
    emoji: '🍽️',
    description: 'Cardápio, pedidos e situações em restaurante.',
    practiceRoute: routes.farm,
    practiceLabel: 'Praticar no Farm',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 8,
    sortOrder: 4,
  },
  {
    key: 'explorer_hotel',
    worldKey: LearningWorldKey.EXPLORER,
    kind: 'vocabulary',
    title: 'Hotel',
    emoji: '🏨',
    description: 'Check-in, quarto e serviços de hospedagem.',
    practiceRoute: routes.flashDeckReview,
    practiceLabel: 'Revisar vocabulário',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 6,
    sortOrder: 5,
  },
  {
    key: 'explorer_routine',
    worldKey: LearningWorldKey.EXPLORER,
    kind: 'vocabulary',
    title: 'Rotina diária',
    emoji: '⏰',
    description: 'Horários, hábitos e atividades do dia a dia.',
    practiceRoute: routes.farm,
    practiceLabel: 'Praticar no Farm',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 8,
    sortOrder: 6,
  },
  {
    key: 'explorer_hobbies',
    worldKey: LearningWorldKey.EXPLORER,
    kind: 'vocabulary',
    title: 'Hobbies',
    emoji: '🎸',
    description: 'Esportes, lazer e interesses pessoais.',
    practiceRoute: routes.farm,
    practiceLabel: 'Aprender palavras',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 6,
    sortOrder: 7,
  },
  {
    key: 'explorer_grammar_past_simple',
    worldKey: LearningWorldKey.EXPLORER,
    kind: 'grammar',
    title: 'Past Simple',
    emoji: '⏪',
    description: 'Ações passadas com verbos regulares e irregulares.',
    practiceRoute: routes.duels,
    practiceLabel: 'Duelo A2',
    practiceActivity: FarmActivityType.EXERCISE,
    requiredPracticeAmount: 4,
    sortOrder: 8,
  },
  {
    key: 'explorer_grammar_future_will',
    worldKey: LearningWorldKey.EXPLORER,
    kind: 'grammar',
    title: 'Future (Will)',
    emoji: '🔮',
    description: 'Previsões, promessas e decisões espontâneas.',
    practiceRoute: routes.duels,
    practiceLabel: 'Duelo A2',
    practiceActivity: FarmActivityType.EXERCISE,
    requiredPracticeAmount: 3,
    sortOrder: 9,
  },
  {
    key: 'explorer_grammar_going_to',
    worldKey: LearningWorldKey.EXPLORER,
    kind: 'grammar',
    title: 'Going To',
    emoji: '📋',
    description: 'Planos e intenções futuras.',
    practiceRoute: routes.farm,
    practiceLabel: 'Exercícios no Farm',
    practiceActivity: FarmActivityType.EXERCISE,
    requiredPracticeAmount: 4,
    sortOrder: 10,
  },
  {
    key: 'explorer_grammar_comparatives',
    worldKey: LearningWorldKey.EXPLORER,
    kind: 'grammar',
    title: 'Comparatives & Superlatives',
    emoji: '📊',
    description: 'Comparar pessoas, lugares e coisas.',
    practiceRoute: routes.duels,
    practiceLabel: 'Duelo A2',
    practiceActivity: FarmActivityType.EXERCISE,
    requiredPracticeAmount: 3,
    sortOrder: 11,
  },
  {
    key: 'explorer_speaking_daily',
    worldKey: LearningWorldKey.EXPLORER,
    kind: 'speaking',
    title: 'Conversas do cotidiano',
    emoji: '🗣️',
    description: 'Situações simples: compras, restaurante e transporte.',
    practiceRoute: routes.farm,
    practiceLabel: 'Conversação no Farm',
    practiceActivity: FarmActivityType.SPEAKING,
    requiredPracticeAmount: 3,
    sortOrder: 12,
  },
  {
    key: 'explorer_checkpoint_conversation',
    worldKey: LearningWorldKey.EXPLORER,
    kind: 'checkpoint',
    title: 'Checkpoint: conversa de 5 minutos',
    emoji: '🏁',
    description: 'Mantenha uma conversa cotidiana de 5 minutos.',
    practiceRoute: routes.farm,
    practiceLabel: 'Praticar speaking',
    practiceActivity: FarmActivityType.SPEAKING,
    requiredPracticeAmount: 5,
    sortOrder: 13,
  },
]
