import { routes } from '@/constants'
import { FarmActivityType } from '@/types/farm'
import { LearningWorldKey, type LearningCurriculumUnitDefinition } from '@/types/learning-gps'

export const GLOBAL_ENGINEER_CURRICULUM_UNITS: LearningCurriculumUnitDefinition[] = [
  {
    key: 'global_fluency',
    worldKey: LearningWorldKey.GLOBAL_ENGINEER,
    kind: 'vocabulary',
    title: 'Fluência profissional',
    emoji: '🌍',
    description: 'Vocabulário avançado para comunicação no trabalho global.',
    practiceRoute: routes.farm,
    practiceLabel: 'Praticar no Farm',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 10,
    sortOrder: 1,
  },
  {
    key: 'global_interviews',
    worldKey: LearningWorldKey.GLOBAL_ENGINEER,
    kind: 'vocabulary',
    title: 'Entrevistas internacionais',
    emoji: '🎯',
    description: 'Perguntas comportamentais e técnicas em entrevistas.',
    practiceRoute: routes.flashDeckReview,
    practiceLabel: 'Revisar vocabulário',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 8,
    sortOrder: 2,
  },
  {
    key: 'global_networking',
    worldKey: LearningWorldKey.GLOBAL_ENGINEER,
    kind: 'vocabulary',
    title: 'Networking',
    emoji: '🔗',
    description: 'Conferências, conexões e conversas profissionais.',
    practiceRoute: routes.farm,
    practiceLabel: 'Aprender palavras',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 6,
    sortOrder: 3,
  },
  {
    key: 'global_leadership',
    worldKey: LearningWorldKey.GLOBAL_ENGINEER,
    kind: 'vocabulary',
    title: 'Liderança técnica',
    emoji: '👥',
    description: 'Mentoria, decisões estratégicas e gestão de equipes.',
    practiceRoute: routes.farm,
    practiceLabel: 'Praticar no Farm',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 8,
    sortOrder: 4,
  },
  {
    key: 'global_grammar_c1',
    worldKey: LearningWorldKey.GLOBAL_ENGINEER,
    kind: 'grammar',
    title: 'Gramática avançada C1',
    emoji: '📐',
    description: 'Estruturas complexas para argumentação profissional.',
    practiceRoute: routes.duels,
    practiceLabel: 'Duelo C1',
    practiceActivity: FarmActivityType.EXERCISE,
    requiredPracticeAmount: 5,
    sortOrder: 5,
  },
  {
    key: 'global_reading_complex',
    worldKey: LearningWorldKey.GLOBAL_ENGINEER,
    kind: 'vocabulary',
    title: 'Reading: documentação complexa',
    emoji: '📚',
    description: 'RFCs, whitepapers e specs técnicas avançadas.',
    practiceRoute: routes.farm,
    practiceLabel: 'Ler no Farm',
    practiceActivity: FarmActivityType.READING,
    requiredPracticeAmount: 4,
    sortOrder: 6,
  },
  {
    key: 'global_writing_emails',
    worldKey: LearningWorldKey.GLOBAL_ENGINEER,
    kind: 'vocabulary',
    title: 'Writing: e-mails profissionais',
    emoji: '✉️',
    description: 'Propostas, follow-ups e comunicação executiva.',
    practiceRoute: routes.farm,
    practiceLabel: 'Escrever no Farm',
    practiceActivity: FarmActivityType.READING,
    requiredPracticeAmount: 4,
    sortOrder: 7,
  },
  {
    key: 'global_speaking_discussions',
    worldKey: LearningWorldKey.GLOBAL_ENGINEER,
    kind: 'speaking',
    title: 'Speaking: discussões técnicas',
    emoji: '🗣️',
    description: 'Debata arquitetura, trade-offs e decisões em equipe.',
    practiceRoute: routes.farm,
    practiceLabel: 'Conversação no Farm',
    practiceActivity: FarmActivityType.SPEAKING,
    requiredPracticeAmount: 5,
    sortOrder: 8,
  },
  {
    key: 'global_checkpoint_hired',
    worldKey: LearningWorldKey.GLOBAL_ENGINEER,
    kind: 'checkpoint',
    title: 'Checkpoint: contratação internacional',
    emoji: '🏁',
    description: 'Simule entrevista final e onboarding em empresa global.',
    practiceRoute: routes.farm,
    practiceLabel: 'Praticar speaking',
    practiceActivity: FarmActivityType.SPEAKING,
    requiredPracticeAmount: 8,
    sortOrder: 9,
  },
]
