import { routes } from '@/constants'
import { FarmActivityType } from '@/types/farm'
import { LearningWorldKey, type LearningCurriculumUnitDefinition } from '@/types/learning-gps'

export const LEGEND_CURRICULUM_UNITS: LearningCurriculumUnitDefinition[] = [
  {
    key: 'legend_debates',
    worldKey: LearningWorldKey.LEGEND,
    kind: 'vocabulary',
    title: 'Debates',
    emoji: '⚔️',
    description: 'Argumentar, refutar e defender posições com precisão.',
    practiceRoute: routes.farm,
    practiceLabel: 'Praticar no Farm',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 8,
    sortOrder: 1,
  },
  {
    key: 'legend_presentations',
    worldKey: LearningWorldKey.LEGEND,
    kind: 'vocabulary',
    title: 'Apresentações',
    emoji: '🎤',
    description: 'Palestras, keynotes e storytelling persuasivo.',
    practiceRoute: routes.flashDeckReview,
    practiceLabel: 'Revisar vocabulário',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 6,
    sortOrder: 2,
  },
  {
    key: 'legend_negotiation',
    worldKey: LearningWorldKey.LEGEND,
    kind: 'vocabulary',
    title: 'Negociação',
    emoji: '🤝',
    description: 'Acordos, concessões e linguagem diplomática.',
    practiceRoute: routes.farm,
    practiceLabel: 'Aprender palavras',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 6,
    sortOrder: 3,
  },
  {
    key: 'legend_teaching',
    worldKey: LearningWorldKey.LEGEND,
    kind: 'vocabulary',
    title: 'Ensino',
    emoji: '📚',
    description: 'Explicar conceitos, corrigir e mentorar em inglês.',
    practiceRoute: routes.farm,
    practiceLabel: 'Praticar no Farm',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 6,
    sortOrder: 4,
  },
  {
    key: 'legend_grammar_c2',
    worldKey: LearningWorldKey.LEGEND,
    kind: 'grammar',
    title: 'Gramática C2',
    emoji: '📐',
    description: 'Nuances, estilo e precisão em estruturas avançadas.',
    practiceRoute: routes.duels,
    practiceLabel: 'Duelo C2',
    practiceActivity: FarmActivityType.EXERCISE,
    requiredPracticeAmount: 5,
    sortOrder: 5,
  },
  {
    key: 'legend_speaking_mastery',
    worldKey: LearningWorldKey.LEGEND,
    kind: 'speaking',
    title: 'Speaking: domínio oral',
    emoji: '🗣️',
    description: 'Fluência espontânea em qualquer contexto profissional.',
    practiceRoute: routes.farm,
    practiceLabel: 'Conversação no Farm',
    practiceActivity: FarmActivityType.SPEAKING,
    requiredPracticeAmount: 6,
    sortOrder: 6,
  },
  {
    key: 'legend_reading_mastery',
    worldKey: LearningWorldKey.LEGEND,
    kind: 'vocabulary',
    title: 'Reading: textos avançados',
    emoji: '📖',
    description: 'Literatura técnica, acadêmica e jornalismo de alto nível.',
    practiceRoute: routes.farm,
    practiceLabel: 'Ler no Farm',
    practiceActivity: FarmActivityType.READING,
    requiredPracticeAmount: 4,
    sortOrder: 7,
  },
  {
    key: 'legend_checkpoint_mastery',
    worldKey: LearningWorldKey.LEGEND,
    kind: 'checkpoint',
    title: 'Checkpoint: domínio avançado',
    emoji: '👑',
    description: 'Demonstre domínio C2 em debate, apresentação e negociação.',
    practiceRoute: routes.farm,
    practiceLabel: 'Praticar speaking',
    practiceActivity: FarmActivityType.SPEAKING,
    requiredPracticeAmount: 10,
    sortOrder: 8,
  },
]
