import { routes } from '@/constants'
import { FarmActivityType } from '@/types/farm'
import { LearningWorldKey, type LearningCurriculumUnitDefinition } from '@/types/learning-gps'

export const PROFESSIONAL_CURRICULUM_UNITS: LearningCurriculumUnitDefinition[] = [
  {
    key: 'professional_work',
    worldKey: LearningWorldKey.PROFESSIONAL,
    kind: 'vocabulary',
    title: 'Trabalho',
    emoji: '💼',
    description: 'Escritório, cargos, tarefas e ambiente profissional.',
    practiceRoute: routes.farm,
    practiceLabel: 'Praticar no Farm',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 8,
    sortOrder: 1,
  },
  {
    key: 'professional_meetings',
    worldKey: LearningWorldKey.PROFESSIONAL,
    kind: 'vocabulary',
    title: 'Reuniões',
    emoji: '🤝',
    description: 'Agenda, participantes e vocabulário de reuniões.',
    practiceRoute: routes.flashDeckReview,
    practiceLabel: 'Revisar vocabulário',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 6,
    sortOrder: 2,
  },
  {
    key: 'professional_technology',
    worldKey: LearningWorldKey.PROFESSIONAL,
    kind: 'vocabulary',
    title: 'Tecnologia',
    emoji: '💻',
    description: 'Ferramentas digitais, software e termos técnicos básicos.',
    practiceRoute: routes.farm,
    practiceLabel: 'Aprender palavras',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 8,
    sortOrder: 3,
  },
  {
    key: 'professional_companies',
    worldKey: LearningWorldKey.PROFESSIONAL,
    kind: 'vocabulary',
    title: 'Empresas',
    emoji: '🏢',
    description: 'Estrutura organizacional, departamentos e cultura.',
    practiceRoute: routes.farm,
    practiceLabel: 'Praticar no Farm',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 6,
    sortOrder: 4,
  },
  {
    key: 'professional_soft_skills',
    worldKey: LearningWorldKey.PROFESSIONAL,
    kind: 'vocabulary',
    title: 'Soft skills',
    emoji: '🌟',
    description: 'Comunicação, colaboração e feedback profissional.',
    practiceRoute: routes.farm,
    practiceLabel: 'Aprender palavras',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 6,
    sortOrder: 5,
  },
  {
    key: 'professional_grammar_present_perfect',
    worldKey: LearningWorldKey.PROFESSIONAL,
    kind: 'grammar',
    title: 'Present Perfect',
    emoji: '✅',
    description: 'Experiências e resultados com ligação ao presente.',
    practiceRoute: routes.duels,
    practiceLabel: 'Duelo B1',
    practiceActivity: FarmActivityType.EXERCISE,
    requiredPracticeAmount: 4,
    sortOrder: 6,
  },
  {
    key: 'professional_grammar_past_continuous',
    worldKey: LearningWorldKey.PROFESSIONAL,
    kind: 'grammar',
    title: 'Past Continuous',
    emoji: '⏳',
    description: 'Ações em progresso no passado.',
    practiceRoute: routes.duels,
    practiceLabel: 'Duelo B1',
    practiceActivity: FarmActivityType.EXERCISE,
    requiredPracticeAmount: 3,
    sortOrder: 7,
  },
  {
    key: 'professional_grammar_future_continuous',
    worldKey: LearningWorldKey.PROFESSIONAL,
    kind: 'grammar',
    title: 'Future Continuous',
    emoji: '🔜',
    description: 'Ações em progresso no futuro.',
    practiceRoute: routes.farm,
    practiceLabel: 'Exercícios no Farm',
    practiceActivity: FarmActivityType.EXERCISE,
    requiredPracticeAmount: 4,
    sortOrder: 8,
  },
  {
    key: 'professional_grammar_modals',
    worldKey: LearningWorldKey.PROFESSIONAL,
    kind: 'grammar',
    title: 'Modals',
    emoji: '🔑',
    description: 'Can, could, must, should — obrigação e possibilidade.',
    practiceRoute: routes.duels,
    practiceLabel: 'Duelo B1',
    practiceActivity: FarmActivityType.EXERCISE,
    requiredPracticeAmount: 4,
    sortOrder: 9,
  },
  {
    key: 'professional_reading',
    worldKey: LearningWorldKey.PROFESSIONAL,
    kind: 'vocabulary',
    title: 'Reading: artigos simples',
    emoji: '📰',
    description: 'Leia artigos curtos sobre trabalho e tecnologia.',
    practiceRoute: routes.farm,
    practiceLabel: 'Ler no Farm',
    practiceActivity: FarmActivityType.READING,
    requiredPracticeAmount: 3,
    sortOrder: 10,
  },
  {
    key: 'professional_listening',
    worldKey: LearningWorldKey.PROFESSIONAL,
    kind: 'vocabulary',
    title: 'Listening: vídeos técnicos',
    emoji: '🎧',
    description: 'Compreenda vídeos técnicos em ritmo moderado.',
    practiceRoute: routes.farm,
    practiceLabel: 'Ouvir no Farm',
    practiceActivity: FarmActivityType.LISTENING,
    requiredPracticeAmount: 3,
    sortOrder: 11,
  },
  {
    key: 'professional_speaking_meetings',
    worldKey: LearningWorldKey.PROFESSIONAL,
    kind: 'speaking',
    title: 'Speaking: reuniões',
    emoji: '🗣️',
    description: 'Apresente ideias e participe de discussões simples.',
    practiceRoute: routes.farm,
    practiceLabel: 'Conversação no Farm',
    practiceActivity: FarmActivityType.SPEAKING,
    requiredPracticeAmount: 4,
    sortOrder: 12,
  },
  {
    key: 'professional_checkpoint_meetings',
    worldKey: LearningWorldKey.PROFESSIONAL,
    kind: 'checkpoint',
    title: 'Checkpoint: reuniões simples',
    emoji: '🏁',
    description: 'Participe de uma reunião simulada com agenda e feedback.',
    practiceRoute: routes.farm,
    practiceLabel: 'Praticar speaking',
    practiceActivity: FarmActivityType.SPEAKING,
    requiredPracticeAmount: 5,
    sortOrder: 13,
  },
]
