import { routes } from '@/constants'
import { FarmActivityType } from '@/types/farm'
import { LearningWorldKey, type LearningCurriculumUnitDefinition } from '@/types/learning-gps'

export const SURVIVOR_CURRICULUM_UNITS: LearningCurriculumUnitDefinition[] = [
  {
    key: 'survivor_alphabet',
    worldKey: LearningWorldKey.SURVIVOR,
    kind: 'vocabulary',
    title: 'Alfabeto e sons básicos',
    emoji: '🔤',
    description: 'Reconheça letras e pronúncia inicial em palavras simples.',
    practiceRoute: routes.flashDeckReview,
    practiceLabel: 'Revisar no Baralho',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 5,
    sortOrder: 1,
  },
  {
    key: 'survivor_numbers_colors',
    worldKey: LearningWorldKey.SURVIVOR,
    kind: 'vocabulary',
    title: 'Números e cores',
    emoji: '🎨',
    description: 'Conte, identifique cores e use números no dia a dia.',
    practiceRoute: routes.farm,
    practiceLabel: 'Praticar no Farm',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 8,
    sortOrder: 2,
  },
  {
    key: 'survivor_calendar',
    worldKey: LearningWorldKey.SURVIVOR,
    kind: 'vocabulary',
    title: 'Dias e meses',
    emoji: '📅',
    description: 'Dias da semana, meses e sequências temporais básicas.',
    practiceRoute: routes.flashDeckReview,
    practiceLabel: 'Revisar vocabulário',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 6,
    sortOrder: 3,
  },
  {
    key: 'survivor_family',
    worldKey: LearningWorldKey.SURVIVOR,
    kind: 'vocabulary',
    title: 'Família',
    emoji: '👨‍👩‍👧',
    description: 'Membros da família e relações pessoais.',
    practiceRoute: routes.farm,
    practiceLabel: 'Aprender palavras',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 6,
    sortOrder: 4,
  },
  {
    key: 'survivor_home',
    worldKey: LearningWorldKey.SURVIVOR,
    kind: 'vocabulary',
    title: 'Casa e objetos',
    emoji: '🏠',
    description: 'Cômodos, móveis e objetos do cotidiano.',
    practiceRoute: routes.farm,
    practiceLabel: 'Praticar no Farm',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 8,
    sortOrder: 5,
  },
  {
    key: 'survivor_food',
    worldKey: LearningWorldKey.SURVIVOR,
    kind: 'vocabulary',
    title: 'Comida',
    emoji: '🍎',
    description: 'Alimentos, bebidas e frases em restaurante.',
    practiceRoute: routes.farm,
    practiceLabel: 'Aprender palavras',
    practiceActivity: FarmActivityType.VOCABULARY,
    requiredPracticeAmount: 8,
    sortOrder: 6,
  },
  {
    key: 'survivor_grammar_to_be',
    worldKey: LearningWorldKey.SURVIVOR,
    kind: 'grammar',
    title: 'Verb To Be',
    emoji: '⚡',
    description: 'I am, you are, he is — identidade e descrições.',
    practiceRoute: routes.duels,
    practiceLabel: 'Duelo A1',
    practiceActivity: FarmActivityType.EXERCISE,
    requiredPracticeAmount: 3,
    sortOrder: 7,
  },
  {
    key: 'survivor_grammar_articles',
    worldKey: LearningWorldKey.SURVIVOR,
    kind: 'grammar',
    title: 'Articles e pronouns',
    emoji: '📐',
    description: 'A, an, the e pronomes pessoais.',
    practiceRoute: routes.duels,
    practiceLabel: 'Duelo A1',
    practiceActivity: FarmActivityType.EXERCISE,
    requiredPracticeAmount: 3,
    sortOrder: 8,
  },
  {
    key: 'survivor_grammar_present',
    worldKey: LearningWorldKey.SURVIVOR,
    kind: 'grammar',
    title: 'Simple Present',
    emoji: '🔄',
    description: 'Rotinas e hábitos com presente simples.',
    practiceRoute: routes.farm,
    practiceLabel: 'Exercícios no Farm',
    practiceActivity: FarmActivityType.EXERCISE,
    requiredPracticeAmount: 4,
    sortOrder: 9,
  },
  {
    key: 'survivor_grammar_there_is',
    worldKey: LearningWorldKey.SURVIVOR,
    kind: 'grammar',
    title: 'There is / There are',
    emoji: '📍',
    description: 'Descrever lugares e existência de coisas.',
    practiceRoute: routes.duels,
    practiceLabel: 'Duelo A1',
    practiceActivity: FarmActivityType.EXERCISE,
    requiredPracticeAmount: 3,
    sortOrder: 10,
  },
  {
    key: 'survivor_grammar_possessive',
    worldKey: LearningWorldKey.SURVIVOR,
    kind: 'grammar',
    title: 'Possessive adjectives',
    emoji: '🤝',
    description: 'My, your, his, her — posse e pertencimento.',
    practiceRoute: routes.farm,
    practiceLabel: 'Exercícios no Farm',
    practiceActivity: FarmActivityType.EXERCISE,
    requiredPracticeAmount: 4,
    sortOrder: 11,
  },
  {
    key: 'survivor_speaking_intro',
    worldKey: LearningWorldKey.SURVIVOR,
    kind: 'speaking',
    title: 'Apresente-se',
    emoji: '🗣️',
    description: 'Nome, idade, profissão e nacionalidade em voz alta.',
    practiceRoute: routes.farm,
    practiceLabel: 'Conversação no Farm',
    practiceActivity: FarmActivityType.SPEAKING,
    requiredPracticeAmount: 2,
    sortOrder: 12,
  },
  {
    key: 'survivor_checkpoint_conversation',
    worldKey: LearningWorldKey.SURVIVOR,
    kind: 'checkpoint',
    title: 'Checkpoint: conversa de 2 minutos',
    emoji: '🏁',
    description: 'Mantenha uma conversa básica de 2 minutos sobre você.',
    practiceRoute: routes.farm,
    practiceLabel: 'Praticar speaking',
    practiceActivity: FarmActivityType.SPEAKING,
    requiredPracticeAmount: 2,
    sortOrder: 13,
  },
]

export const getSurvivorCurriculum = (): LearningCurriculumUnitDefinition[] =>
  [...SURVIVOR_CURRICULUM_UNITS].sort((a, b) => a.sortOrder - b.sortOrder)
