import type { DuelPatent } from '@/types/duel';
import { DUEL_PATENT_LABELS } from '@/types/duel';

export const DUEL_UI = {
  screenTitle: 'Duelos de Inglês',
  screenSubtitle: 'Treine vocabulário em batalhas rápidas',
  emoji: '⚔️',
  arenaTitle: 'Arena do Coliseu',
  startBattle: 'Iniciar duelo',
  battleTitle: 'Duelo',
  playerLabel: 'Você',
  enemyLabel: 'Inimigo',
  comboLabel: (streak: number) => (streak >= 3 ? `Combo ×2 (${streak})` : streak > 0 ? `Combo ${streak}` : ''),
  questionProgress: (current: number, total: number) => `Pergunta ${current} de ${total}`,
  correctFeedback: 'Acerto!',
  wrongFeedback: 'Erro — contra-ataque!',
  victoryTitle: 'Vitória!',
  victoryBody: 'O Slime derreteu. Recompensas na mochila.',
  defeatTitle: 'Derrota',
  defeatBody: 'Consolation XP garantido. Revise no Baralho e volte.',
  backToArena: 'Voltar à arena',
  patentLabel: (patent: DuelPatent) => `Patente ${DUEL_PATENT_LABELS[patent]}`,
  damageDealt: (amount: number) => `−${amount} HP`,
  damageTaken: (amount: number) => `−${amount} HP`,
  rewardsLine: (xp: number, coins: number) => `+${xp} XP · +${coins} moedas`,
  consolationLine: (xp: number) => `+${xp} XP de consolo`,
  dojoRewardsNote: 'Dojo — recompensas reduzidas (treino)',
  staminaTitle: 'Stamina',
  staminaLine: (current: number, max: number) => `${current}/${max}`,
  dailyRankedLine: (done: number, cap: number) => `${done}/${cap} duelos ranqueados hoje`,
  staminaRegenHint: '+1 stamina a cada 4h offline (máx. 5)',
  nextStaminaRegen: (iso: string) => {
    const date = new Date(iso);
    const hours = date.getHours().toString().padStart(2, '0');
    const minutes = date.getMinutes().toString().padStart(2, '0');
    return `Próxima stamina ~${hours}:${minutes}`;
  },
  rankedBattle: 'Duelo ranqueado',
  rankedDisabled: 'Sem stamina ou limite diário atingido',
  dojoBattle: 'Dojo (treino)',
  dojoHint: 'Sem gastar stamina · XP ×0,5',
  patentExam: 'Prova de patente',
  patentExamHint: '15 perguntas · 80% para virar Morador',
  rematchReview: 'Revisar erros',
  rematchHint: 'Até 3 perguntas do último duelo',
  rematchUnavailable: 'Nenhum duelo perdido recente com erros',
  criticalHit: 'Golpe crítico!',
  examTitle: 'Prova de patente',
  examProgress: (current: number, total: number) => `Pergunta ${current} de ${total}`,
  examPass: 'Aprovado! Você é Morador agora.',
  examFail: 'Não passou desta vez. Treine no Dojo e tente de novo.',
  examScore: (correct: number, total: number) => `${correct}/${total} acertos`,
  rankedPoolHint: 'Ranqueado usa pool A2+ (sem pacote só A1)',
  touristPoolHint: 'Ranqueado: pool viagem A1',
  cardDuelBattle: 'Duelo de cartas',
  cardDuelHint: '5 cartas na mesa · sem stamina',
  cardDuelUnavailable: 'Revise o Baralho ou aguarde cartas due',
  saveCardTitle: 'Salvar no Baralho?',
  saveCardBody: 'Guarde esta palavra com um toque para revisar depois.',
  saveCardFrontLabel: 'Inglês',
  saveCardBackLabel: 'Português',
  saveCardConfirm: 'Salvar carta',
  saveCardDismiss: 'Agora não',
  saveCardSuccess: 'Carta salva no Baralho Vivo!',
  arenaBonusGranted: 'Bônus da arena: +1 stamina hoje.',
  weeklyBoss: 'Boss semanal',
  weeklyBossHint: '1× por semana · bônus de moedas',
  weeklyBossDefeated: 'Boss derrotado esta semana. Volte na próxima segunda.',
  timerLabel: (sec: number) => `⏱ ${sec}s`,
  timerAccessibility: (sec: number) => `Tempo restante ${sec} segundos`,
  patentExamHintDynamic: (target: string) => `15 perguntas · 80% para virar ${target}`,
} as const;
