export const PET_LEAGUE_UI = {
  subtitle: 'Duelos semanais contra fantasmas da sua divisão.',
  seasonTitle: 'Temporada semanal',
  daysLeft: (n: number) => (n === 1 ? '1 dia restante' : `${n} dias restantes`),
  seasonProgress: 'Progresso da semana',
  accountWins: 'Vitórias totais',
  accountPeak: 'Melhor rating',
  nextTier: 'Próxima meta',
  nextTierDone: 'Todas as metas alcançadas!',
  nextTierProgress: (current: number, target: number, label: string) =>
    `${current}/${target} para ${label}`,
  resetsMonday: 'Reinicia segunda 00:00',
  stepPick: '1 · Pet',
  stepFight: '2 · Duelo',
  stepRewards: '3 · Prêmios',
  fighterTitle: 'Seu lutador',
  fighterHint: 'Rating = nível, stats, GEN, traits e sequência de vitórias.',
  pickPet: 'Trocar lutador',
  divisionLabel: 'Divisão',
  ratingLabel: 'Rating',
  winsLabel: 'Vitórias',
  streakLabel: 'Sequência',
  recordLabel: 'Placar',
  recordValue: (w: number, l: number) => `${w}V · ${l}D`,
  battlesToday: 'Lutas hoje',
  opponentsTitle: 'Arena',
  opponentsHint: 'Oponentes da mesma divisão · lista muda todo dia',
  recommended: 'Melhor chance',
  battleCta: 'Duelar',
  advantage: (diff: number) => (diff >= 0 ? `+${diff} rating` : `${diff} rating`),
  rewardsTitle: 'Recompensas da temporada',
  rewardsHint: 'Conta vitórias de todos os pets · resgate uma vez por tier',
  rewardsToggleShow: 'Ver recompensas',
  rewardsToggleHide: 'Ocultar recompensas',
  claim: 'Resgatar',
  claimed: 'Resgatado',
  locked: 'Em progresso',
  winMessage: (coins: number) => `Vitória! +${coins} moedas`,
  lossMessage: 'Derrota. Sequência zerada.',
  chanceLabel: (pct: number) => `${Math.round(pct * 100)}% chance de vitória`,
  noBattlesLeft: 'Limite diário atingido. Volte amanhã.',
  goldUnlockHint: 'Meta Ouro ativa — Ilha do Céu liberada nas aventuras!',
  emptyOpponents: 'Selecione um pet para ver oponentes.',
} as const;
