export const PET_ACADEMY_UI = {
  subtitle: 'Envie pets para aulas idle e evolua atributos.',
  capacityTitle: 'Salas em uso',
  activeTitle: 'Estudando agora',
  emptyActive: 'Nenhuma aula em andamento.',
  emptyActiveHint: 'Escolha uma trilha e um pet abaixo.',
  ready: 'Aula concluída!',
  returningIn: (label: string) => `Termina em ${label}`,
  collect: 'Coletar',
  collectAll: 'Coletar todas prontas',
  startTitle: 'Nova matrícula',
  previewTitle: 'Resumo da aula',
  pickPet: 'Quem vai estudar?',
  pickTrack: 'Trilha de estudo',
  startCta: 'Matricular na academia',
  rewardsHint: 'XP do pet + 1–3 pontos de stat · 5% chance de trait bônus',
  statFocus: (label: string) => `Foco: ${label}`,
  durationLabel: (hours: string) => `${hours} de aula`,
} as const;
