export const PET_FARM_UI = {
  title: 'Fazenda de Pets',
  subtitle: 'Pasto, cruzamento e coleção',
  bonuses: 'Bônus ativos',
  pasture: 'Pasto de passivas',
  barn: 'Celeiro',
  incubator: 'Incubadora',
  emptySlot: 'Vazio',
  lockedSlot: 'Melhore o pasto',
  assign: 'Colocar no pasto',
  remove: 'Removido do pasto.',
  upgradesTitle: 'Melhorar fazenda',
  breedingTitle: 'Laboratório de cruzamento',
  encyclopediaTitle: 'Enciclopédia de cruzamento',
  glossaryTitle: 'Glossário de pets',
  mother: 'Mãe ♀',
  father: 'Pai ♂',
  outcomes: 'Filhos possíveis',
  startBreed: 'Iniciar cruzamento',
  selectMother: 'Selecione a mãe',
  selectFather: 'Selecione o pai',
  upgrade: 'Melhorar',
  maxLevel: 'Nível máximo',
  goFarm: 'Abrir fazenda',
  mapTitle: 'Ilha dos Pets',
  mapSubtitle: 'Toque em um prédio',
  pastureBuilding: 'Pasto',
  breedingBuilding: 'Laboratório',
  incubatorBuilding: 'Incubadora',
  barnBuilding: 'Celeiro',
  upgradesBuilding: 'Melhorias',
  encyclopediaBuilding: 'Enciclopédia',
  glossaryBuilding: 'Glossário',
  detailTitle: 'Detalhes do pet',
  setActive: 'Tornar companheiro',
  activeCompanion: 'Companheiro ativo',
  stats: 'Atributos',
  passive: 'Passivo efetivo',
  lineage: 'Linhagem',
  noParents: 'Sem registro de pais (GEN 1)',
  inPasture: 'No pasto',
  openPasture: 'Gerenciar pasto',
  viewDetails: 'Ver detalhes',
} as const;
