export const PET_ADVENTURES_UI = {
  subtitle: 'Envie pets em expedições idle e colete recompensas.',
  capacityTitle: 'Capacidade',
  slotsShortLabel: 'Curtas',
  slotsLongLabel: 'Longas',
  weekly24hLabel: '24h / sem',
  activeTitle: 'Em expedição',
  emptyActive: 'Nenhuma expedição ativa.',
  emptyActiveHint: 'Monte uma nova expedição abaixo.',
  ready: 'Pronto para coletar!',
  returningIn: (label: string) => `Retorno em ${label}`,
  collect: 'Coletar',
  collectAll: 'Coletar todas prontas',
  startTitle: 'Nova expedição',
  previewTitle: 'Resumo da expedição',
  pickPet: 'Quem vai na expedição?',
  pickBiome: 'Destino',
  pickDuration: 'Tempo fora',
  durationShort: 'Missões curtas (15m – 4h)',
  durationLong: 'Missões longas (8h – 24h)',
  successChance: 'Chance de sucesso',
  rewardsEstimate: 'Recompensa estimada',
  startCta: 'Enviar em expedição',
  locked: 'Bloqueado',
  rewardCoins: (min: number, max: number) => `${min}–${max} 🪙`,
  rewardXp: (xp: number) => `+${xp} XP pet`,
  rewardSp: (sp: number) => `+${sp} SP`,
  rewardLoot: 'Loot box',
  walking: 'Explorando…',
} as const;
