export const PET_INSTANCE_HUB_UI = {
  tabOverview: 'Resumo',
  tabMemories: 'Memórias',
  tabBreeding: 'Cruzamentos',
  tabAchievements: 'Conquistas',
  tabEquip: 'Equipar',
  actionsTitle: 'Ações',
  setActive: 'Tornar companheiro',
  openPasture: 'Pasto / celeiro',
  openBreed: 'Cruzamento',
  openAdventure: 'Aventura',
  openAcademy: 'Academia',
  comingSoonAction: 'Em breve (22.6+)',
  achievementsSoon: 'Conquistas por instância chegam em breve.',
  breedHistoryEmpty: 'Este pet ainda não participou de cruzamentos registrados.',
  breedHistoryTitle: 'Histórico de cruzamento',
  roleMother: 'Como mãe ♀',
  roleFather: 'Como pai ♂',
} as const;
