/**
 * Semantic sound vocabulary — English Quest.
 * Assets live in `assets/audio/`; playback via `AudioDirector` + `audio-event-map.ts`.
 * @see docs/AUDIO_SYSTEM.md
 */
export const AUDIO_DOMAINS = [
  'mission',
  'loot',
  'city',
  'pet',
  'focus',
  'meta',
  'learning',
  'economy',
] as const

export type AudioDomain = (typeof AUDIO_DOMAINS)[number]

export const AUDIO_DOMAIN_LABELS: Record<AudioDomain, string> = {
  mission: 'Missões diárias, semanais, rotinas e cadeias POI',
  loot: 'Recebimento e revelação de loot boxes',
  city: 'Cidade, POIs, lexicon e eventos locais',
  pet: 'Companion — interação, memórias e evolução (UI modal)',
  focus: 'Sessões de foco — início e conclusão',
  meta: 'Level up, conquistas, títulos, prestígio e contratos',
  learning: 'Vault, duelos, flash deck e palavras',
  economy: 'Loja, moedas, escudos e colecionáveis',
}

/** Game events wired to SFX in `handleGameEventAudio`. */
export const GAME_EVENTS_WITH_AUDIO = [
  'XP_GAINED',
  'PLAYER_LEVEL_UP',
  'DAILY_MISSION_COMPLETED',
  'LOCAL_MISSION_COMPLETED',
  'WEEKLY_MISSION_CLAIMED',
  'ROUTINE_COMPLETED',
  'CITY_EVENT_MISSION_COMPLETED',
  'POI_CHAIN_STEP_CLAIMED',
  'POI_CHAIN_COMPLETED',
  'STUDY_DAY_RECORDED',
  'STREAK_BROKEN',
  'LOOT_BOX_RECEIVED',
  'LOOT_BOX_OPENED',
  'SHOP_PURCHASE_COMPLETED',
  'CITY_BUILDING_UNLOCKED',
  'POI_VISITED',
  'DISTRICT_UNLOCKED',
  'POI_LEVEL_UP',
  'LEXICON_BRICK_PLACED',
  'LEXICON_BRICK_CRACKED',
  'LEXICON_BRICK_REPAIRED',
  'MEMORY_WALL_COMPLETED',
  'CITY_RESOURCE_DELIVERED',
  'POI_PROJECT_COMPLETED',
  'CITY_EVENT_STARTED',
  'PET_INTERACTION',
  'PET_MEMORY_CREATED',
  'PET_NAMED',
  'FOCUS_SESSION_STARTED',
  'FOCUS_SESSION_COMPLETED',
  'ACHIEVEMENT_UNLOCKED',
  'TITLE_UNLOCKED',
  'PRESTIGE_ASCENDED',
  'CONTRACT_STARTED',
  'CONTRACT_COMPLETED',
  'CONTRACT_FAILED',
  'SHIELD_EARNED',
  'SHIELD_USED',
  'JOURNAL_ENTRY_REVIEWED',
  'JOURNAL_LINK_CREATED',
  'PUNISHMENT_WARNING',
  'DUEL_WON',
  'DUEL_LOST',
  'WORDS_LEARNED',
  'FLASH_SESSION_DONE',
  'COLLECTIBLE_DISCOVERED',
] as const

export type GameEventWithAudio = (typeof GAME_EVENTS_WITH_AUDIO)[number]

export const EVENT_AUDIO_DOMAIN: Record<GameEventWithAudio, AudioDomain> = {
  XP_GAINED: 'meta',
  PLAYER_LEVEL_UP: 'meta',
  DAILY_MISSION_COMPLETED: 'mission',
  LOCAL_MISSION_COMPLETED: 'mission',
  WEEKLY_MISSION_CLAIMED: 'mission',
  ROUTINE_COMPLETED: 'mission',
  CITY_EVENT_MISSION_COMPLETED: 'mission',
  POI_CHAIN_STEP_CLAIMED: 'mission',
  POI_CHAIN_COMPLETED: 'mission',
  STUDY_DAY_RECORDED: 'mission',
  STREAK_BROKEN: 'mission',
  LOOT_BOX_RECEIVED: 'loot',
  LOOT_BOX_OPENED: 'loot',
  SHOP_PURCHASE_COMPLETED: 'economy',
  CITY_BUILDING_UNLOCKED: 'city',
  POI_VISITED: 'city',
  DISTRICT_UNLOCKED: 'city',
  POI_LEVEL_UP: 'city',
  LEXICON_BRICK_PLACED: 'city',
  LEXICON_BRICK_CRACKED: 'city',
  LEXICON_BRICK_REPAIRED: 'city',
  MEMORY_WALL_COMPLETED: 'city',
  CITY_RESOURCE_DELIVERED: 'city',
  POI_PROJECT_COMPLETED: 'city',
  CITY_EVENT_STARTED: 'city',
  PET_INTERACTION: 'pet',
  PET_MEMORY_CREATED: 'pet',
  PET_NAMED: 'pet',
  FOCUS_SESSION_STARTED: 'focus',
  FOCUS_SESSION_COMPLETED: 'focus',
  ACHIEVEMENT_UNLOCKED: 'meta',
  TITLE_UNLOCKED: 'meta',
  PRESTIGE_ASCENDED: 'meta',
  CONTRACT_STARTED: 'meta',
  CONTRACT_COMPLETED: 'meta',
  CONTRACT_FAILED: 'meta',
  SHIELD_EARNED: 'economy',
  SHIELD_USED: 'economy',
  JOURNAL_ENTRY_REVIEWED: 'learning',
  JOURNAL_LINK_CREATED: 'learning',
  PUNISHMENT_WARNING: 'meta',
  DUEL_WON: 'learning',
  DUEL_LOST: 'learning',
  WORDS_LEARNED: 'learning',
  FLASH_SESSION_DONE: 'learning',
  COLLECTIBLE_DISCOVERED: 'economy',
}

/** Milestone SFX still play when `studySilentMode` is on (`priority: 'high'`). */
export const AUDIO_SILENT_MODE_ALLOWLIST: GameEventWithAudio[] = [
  'PLAYER_LEVEL_UP',
  'DAILY_MISSION_COMPLETED',
  'LOCAL_MISSION_COMPLETED',
  'WEEKLY_MISSION_CLAIMED',
  'ROUTINE_COMPLETED',
  'POI_CHAIN_COMPLETED',
  'STUDY_DAY_RECORDED',
  'LOOT_BOX_OPENED',
  'CITY_BUILDING_UNLOCKED',
  'DISTRICT_UNLOCKED',
  'MEMORY_WALL_COMPLETED',
  'POI_PROJECT_COMPLETED',
  'FOCUS_SESSION_COMPLETED',
  'ACHIEVEMENT_UNLOCKED',
  'TITLE_UNLOCKED',
  'PRESTIGE_ASCENDED',
  'CONTRACT_COMPLETED',
  'DUEL_WON',
  'COLLECTIBLE_DISCOVERED',
]
