export const routes = {
  tabs: {
    home: '/',
    quests: '/(tabs)/quests',
    knowledge: '/(tabs)/knowledge',
    menu: '/(tabs)/menu',
    profile: '/(tabs)/profile',
  },
  inventory: '/inventory',
  shop: '/shop',
  pet: '/pet',
  petFarm: '/pet-farm',
  petFarmPasture: '/pet-farm/pasture',
  petFarmBarn: '/pet-farm/barn',
  petFarmIncubator: '/pet-farm/incubator',
  petFarmInstance: '/pet-farm/instance',
  petFarmUpgrades: '/pet-farm/upgrades',
  petFarmBreeding: '/pet-farm/breeding',
  petFarmEncyclopedia: '/pet-farm/encyclopedia',
  petFarmGlossary: '/pet-farm/glossary',
  petFarmMap: '/pet-farm/map',
  petFarmAdventures: '/pet-farm/adventures',
  petFarmAcademy: '/pet-farm/academy',
  petFarmLeague: '/pet-farm/league',
  petFarmHall: '/pet-farm/hall',
  lootBoxes: '/loot-boxes',
  achievements: '/achievements',
  titles: '/titles',
  city: '/city',
  contracts: '/contracts',
  statistics: '/statistics',
  career: '/career',
  metagame: '/metagame',
  farm: '/farm',
  collectionBook: '/collection-book',
  lootBoxCatalog: '/loot-box-catalog',
  prestige: '/prestige',
  focusMode: '/focus-mode',
  focusModeSession: '/focus-mode/session',
  /** Baralho Vivo — gated by `featureFlags.flashDeckEnabled` */
  flashDeck: '/flash-deck',
  flashDeckCreate: '/flash-deck/create',
  flashDeckReview: '/flash-deck/review',
  flashDeckDeck: '/flash-deck/deck',
  flashDeckCard: '/flash-deck/card',
  /** Duelos de Inglês — gated by `featureFlags.duelsEnabled` */
  duels: '/duels',
  duelsBattle: '/duels/battle',
  duelsPatentExam: '/duels/patent-exam',
  duelsRematchReview: '/duels/rematch-review',
  learningInsights: '/learning-insights',
  routines: '/routines',
  englishJournal: '/english-journal',
} as const;
