export const PROFILE_UI = {
  screenTitle: 'Perfil',
  screenSubtitle: 'Quem sou eu e como personalizo minha jornada',
  playerEditLabel: 'Editar nome',
  playerLevelLabel: 'Nível',
  frameLabel: 'Moldura',
  badgeLabel: 'Emblema',
  xpLevelLabel: 'XP do nível',
  xpTotalLabel: 'XP total',
  achievementsLabel: 'Conquistas',
  changeTitle: 'Alterar título equipado',
  equippedTitle: 'Título equipado',
  favoritePet: 'Pet favorito',
  noPetYet: 'Nenhum pet ativo ainda',
  viewPet: 'Ver pet',
  themeLabel: 'Tema visual',
  themeHint: 'Tema escuro premium (mais temas em breve)',
  routinesLink: 'Rotinas e hábitos',
  routinesLinkHint: 'Gerenciar lembretes diários',
  versionLabel: 'Versão',
  aboutBody: 'RPG de evolução profissional através do inglês.',
  playerHeroLabel: 'Seu personagem',
  exploreHeroTitle: 'Mapa do aventureiro',
  exploreHeroSubtitle: 'Progresso médio no mundo',
  exploreNoContract: 'Nenhum contrato ativo — aceite um desafio!',
  exploreEndgameMore: 'Desbloquear Endgame',
  exploreEndgameLess: 'Ocultar Endgame',
  sections: {
    personalization: {
      title: 'Personalização',
      emoji: '🎭',
      subtitle: 'Avatar, título, pet e aparência',
    },
    gameplay: {
      title: 'Gameplay',
      emoji: '⚔️',
      subtitle: 'Dificuldade e rotinas',
    },
    notifications: {
      title: 'Notificações',
      emoji: '🔔',
      subtitle: 'Streak, pet, rotinas e revisões',
    },
    audio: {
      title: 'Áudio',
      emoji: '🔊',
      subtitle: 'Sons, música e vibração',
    },
    appearance: {
      title: 'Aparência',
      emoji: '✨',
      subtitle: 'Tema e modo foco',
    },
    backup: {
      title: 'Backup',
      emoji: '💾',
      subtitle: 'Exportar e restaurar progresso',
    },
    account: {
      title: 'Conta',
      emoji: 'ℹ️',
      subtitle: 'Sobre o app e versão',
    },
  },
} as const
