import { LootBoxRarity } from '@/types/inventory';
import { PetStage } from '@/types/pet';
import {
  AchievementCategory,
  AchievementRewardType,
  type AchievementDefinition,
} from '@/types/achievement';

import { EXTENDED_ACHIEVEMENTS } from '@/features/game-design/catalogs/extended-content';

const BASE_ACHIEVEMENTS: AchievementDefinition[] = [
  {
    key: 'first_day',
    name: 'Primeiro Dia',
    description: 'Complete seu primeiro dia de estudo.',
    category: AchievementCategory.STREAK,
    metric: 'total_study_days',
    target: 1,
    icon: '🌱',
    rewards: [{ type: AchievementRewardType.COINS, amount: 25, label: '25 moedas' }],
  },
  {
    key: 'streak_7',
    name: '7 Dias',
    description: 'Mantenha uma sequência de 7 dias.',
    category: AchievementCategory.STREAK,
    metric: 'best_streak',
    target: 7,
    icon: '🔥',
    rewards: [
      { type: AchievementRewardType.COINS, amount: 50, label: '50 moedas' },
      { type: AchievementRewardType.SHIELD, amount: 1, label: '1 escudo' },
    ],
  },
  {
    key: 'streak_30',
    name: '30 Dias',
    description: 'Mantenha uma sequência de 30 dias.',
    category: AchievementCategory.STREAK,
    metric: 'best_streak',
    target: 30,
    icon: '⚡',
    rewards: [
      { type: AchievementRewardType.COINS, amount: 150, label: '150 moedas' },
      { type: AchievementRewardType.LOOT_BOX, rarity: LootBoxRarity.RARE, label: 'Loot Box Rara' },
    ],
  },
  {
    key: 'streak_100',
    name: '100 Dias',
    description: 'Mantenha uma sequência de 100 dias.',
    category: AchievementCategory.STREAK,
    metric: 'best_streak',
    target: 100,
    icon: '💎',
    rewards: [
      { type: AchievementRewardType.COINS, amount: 500, label: '500 moedas' },
      { type: AchievementRewardType.LOOT_BOX, rarity: LootBoxRarity.EPIC, label: 'Loot Box Épica' },
    ],
  },
  {
    key: 'first_quest',
    name: 'Primeira Missão',
    description: 'Complete sua primeira missão diária.',
    category: AchievementCategory.MISSIONS,
    metric: 'total_missions_completed',
    target: 1,
    icon: '📜',
    rewards: [{ type: AchievementRewardType.COINS, amount: 30, label: '30 moedas' }],
  },
  {
    key: 'missions_10',
    name: '10 Missões',
    description: 'Complete 10 missões diárias.',
    category: AchievementCategory.MISSIONS,
    metric: 'total_missions_completed',
    target: 10,
    icon: '📋',
    rewards: [{ type: AchievementRewardType.COINS, amount: 75, label: '75 moedas' }],
  },
  {
    key: 'missions_50',
    name: '50 Missões',
    description: 'Complete 50 missões diárias.',
    category: AchievementCategory.MISSIONS,
    metric: 'total_missions_completed',
    target: 50,
    icon: '🗂️',
    rewards: [
      { type: AchievementRewardType.COINS, amount: 200, label: '200 moedas' },
      { type: AchievementRewardType.SHIELD, amount: 1, label: '1 escudo' },
    ],
  },
  {
    key: 'missions_100',
    name: '100 Missões',
    description: 'Complete 100 missões diárias.',
    category: AchievementCategory.MISSIONS,
    metric: 'total_missions_completed',
    target: 100,
    icon: '🏆',
    rewards: [
      { type: AchievementRewardType.COINS, amount: 400, label: '400 moedas' },
      { type: AchievementRewardType.LOOT_BOX, rarity: LootBoxRarity.RARE, label: 'Loot Box Rara' },
    ],
  },
  {
    key: 'xp_1000',
    name: '1.000 XP',
    description: 'Acumule 1.000 XP ao longo da jornada.',
    category: AchievementCategory.XP,
    metric: 'total_xp_earned',
    target: 1000,
    icon: '✨',
    rewards: [{ type: AchievementRewardType.COINS, amount: 100, label: '100 moedas' }],
  },
  {
    key: 'xp_5000',
    name: '5.000 XP',
    description: 'Acumule 5.000 XP ao longo da jornada.',
    category: AchievementCategory.XP,
    metric: 'total_xp_earned',
    target: 5000,
    icon: '🌟',
    rewards: [
      { type: AchievementRewardType.COINS, amount: 250, label: '250 moedas' },
      { type: AchievementRewardType.SHIELD, amount: 1, label: '1 escudo' },
    ],
  },
  {
    key: 'xp_10000',
    name: '10.000 XP',
    description: 'Acumule 10.000 XP ao longo da jornada.',
    category: AchievementCategory.XP,
    metric: 'total_xp_earned',
    target: 10000,
    icon: '💫',
    rewards: [
      { type: AchievementRewardType.COINS, amount: 500, label: '500 moedas' },
      { type: AchievementRewardType.LOOT_BOX, rarity: LootBoxRarity.EPIC, label: 'Loot Box Épica' },
    ],
  },
  {
    key: 'level_5',
    name: 'Nível 5',
    description: 'Alcance o nível 5.',
    category: AchievementCategory.LEVEL,
    metric: 'player_level',
    target: 5,
    icon: '🎖️',
    rewards: [{ type: AchievementRewardType.COINS, amount: 75, label: '75 moedas' }],
  },
  {
    key: 'level_10',
    name: 'Nível 10',
    description: 'Alcance o nível 10.',
    category: AchievementCategory.LEVEL,
    metric: 'player_level',
    target: 10,
    icon: '🥇',
    rewards: [{ type: AchievementRewardType.COINS, amount: 150, label: '150 moedas' }],
  },
  {
    key: 'level_25',
    name: 'Nível 25',
    description: 'Alcance o nível 25.',
    category: AchievementCategory.LEVEL,
    metric: 'player_level',
    target: 25,
    icon: '🏅',
    rewards: [
      { type: AchievementRewardType.COINS, amount: 300, label: '300 moedas' },
      { type: AchievementRewardType.LOOT_BOX, rarity: LootBoxRarity.RARE, label: 'Loot Box Rara' },
    ],
  },
  {
    key: 'level_50',
    name: 'Nível 50',
    description: 'Alcance o nível 50.',
    category: AchievementCategory.LEVEL,
    metric: 'player_level',
    target: 50,
    icon: '👑',
    rewards: [
      { type: AchievementRewardType.COINS, amount: 750, label: '750 moedas' },
      { type: AchievementRewardType.LOOT_BOX, rarity: LootBoxRarity.LEGENDARY, label: 'Loot Box Lendária' },
    ],
  },
  {
    key: 'pet_baby',
    name: 'Baby Pet',
    description: 'Evolua seu pet para o estágio Baby.',
    category: AchievementCategory.PET,
    metric: 'pet_stage',
    target: PetStage.BABY,
    icon: '🐣',
    rewards: [{ type: AchievementRewardType.COINS, amount: 100, label: '100 moedas' }],
  },
  {
    key: 'pet_teen',
    name: 'Teen Pet',
    description: 'Evolua seu pet para o estágio Teen.',
    category: AchievementCategory.PET,
    metric: 'pet_stage',
    target: PetStage.TEEN,
    icon: '🐥',
    rewards: [{ type: AchievementRewardType.COINS, amount: 200, label: '200 moedas' }],
  },
  {
    key: 'pet_adult',
    name: 'Adult Pet',
    description: 'Evolua seu pet para o estágio Adult.',
    category: AchievementCategory.PET,
    metric: 'pet_stage',
    target: PetStage.ADULT,
    icon: '🐦',
    rewards: [
      { type: AchievementRewardType.COINS, amount: 400, label: '400 moedas' },
      { type: AchievementRewardType.SHIELD, amount: 1, label: '1 escudo' },
    ],
  },
  {
    key: 'pet_legendary',
    name: 'Legendary Pet',
    description: 'Evolua seu pet para o estágio Legendary.',
    category: AchievementCategory.PET,
    metric: 'pet_stage',
    target: PetStage.LEGENDARY,
    icon: '🦅',
    rewards: [
      { type: AchievementRewardType.COINS, amount: 1000, label: '1000 moedas' },
      { type: AchievementRewardType.LOOT_BOX, rarity: LootBoxRarity.LEGENDARY, label: 'Loot Box Lendária' },
    ],
  },
  {
    key: 'first_loot_box',
    name: 'Primeira Loot Box',
    description: 'Abra sua primeira Loot Box.',
    category: AchievementCategory.LOOT_BOXES,
    metric: 'total_loot_boxes_opened',
    target: 1,
    icon: '🎁',
    rewards: [{ type: AchievementRewardType.COINS, amount: 50, label: '50 moedas' }],
  },
  {
    key: 'loot_boxes_10',
    name: '10 Loot Boxes',
    description: 'Abra 10 Loot Boxes.',
    category: AchievementCategory.LOOT_BOXES,
    metric: 'total_loot_boxes_opened',
    target: 10,
    icon: '📦',
    rewards: [
      { type: AchievementRewardType.COINS, amount: 150, label: '150 moedas' },
      { type: AchievementRewardType.LOOT_BOX, rarity: LootBoxRarity.COMMON, label: 'Loot Box Comum' },
    ],
  },
  {
    key: 'loot_boxes_50',
    name: '50 Loot Boxes',
    description: 'Abra 50 Loot Boxes.',
    category: AchievementCategory.LOOT_BOXES,
    metric: 'total_loot_boxes_opened',
    target: 50,
    icon: '🧰',
    rewards: [
      { type: AchievementRewardType.COINS, amount: 400, label: '400 moedas' },
      { type: AchievementRewardType.LOOT_BOX, rarity: LootBoxRarity.EPIC, label: 'Loot Box Épica' },
    ],
  },
  {
    key: 'duel_first_win',
    name: 'Primeira vitória',
    description: 'Vença seu primeiro duelo.',
    category: AchievementCategory.MISSIONS,
    metric: 'total_duel_wins',
    target: 1,
    icon: '⚔️',
    rewards: [{ type: AchievementRewardType.COINS, amount: 40, label: '40 moedas' }],
  },
  {
    key: 'duel_wins_10',
    name: '10 vitórias',
    description: 'Vença 10 duelos.',
    category: AchievementCategory.MISSIONS,
    metric: 'total_duel_wins',
    target: 10,
    icon: '🏟️',
    rewards: [
      { type: AchievementRewardType.COINS, amount: 90, label: '90 moedas' },
      { type: AchievementRewardType.SHIELD, amount: 1, label: '1 escudo' },
    ],
  },
  {
    key: 'flash_reviews_25',
    name: 'Mesa ativa',
    description: 'Revise 25 cartas no Baralho Vivo.',
    category: AchievementCategory.MISSIONS,
    metric: 'total_flash_reviews',
    target: 25,
    icon: '📒',
    rewards: [{ type: AchievementRewardType.COINS, amount: 60, label: '60 moedas' }],
  },
];

export const ACHIEVEMENT_DEFINITIONS: AchievementDefinition[] = [
  ...BASE_ACHIEVEMENTS,
  ...EXTENDED_ACHIEVEMENTS,
];

export const ACHIEVEMENTS_BY_KEY = Object.fromEntries(
  ACHIEVEMENT_DEFINITIONS.map((achievement) => [achievement.key, achievement]),
) as Record<string, AchievementDefinition>;

export const CATEGORY_LABELS: Record<string, string> = {
  [AchievementCategory.STREAK]: 'Streak',
  [AchievementCategory.MISSIONS]: 'Missões',
  [AchievementCategory.XP]: 'XP',
  [AchievementCategory.LEVEL]: 'Nível',
  [AchievementCategory.PET]: 'Pet',
  [AchievementCategory.LOOT_BOXES]: 'Loot Boxes',
};
