import type { CityEventDefinition } from '@/types/city-event';

export const CITY_EVENTS_CATALOG: CityEventDefinition[] = [
  {
    eventKey: 'christmas_2026',
    name: 'Winter in the City',
    tabLabel: 'Natal',
    emoji: '🎄',
    description:
      'Natal na cidade: mercado de inverno, vocabulário festivo e contratos especiais nos comércios.',
    priority: 100,
    major: true,
    schedule: {
      type: 'fixed_annual',
      startMonth: 12,
      startDay: 1,
      endMonth: 12,
      endDay: 26,
    },
    vocabPackKey: 'christmas_2026',
    mapThemeKey: 'christmas',
    spiritLabel: 'Espírito natalino',
    temporaryPoiKeys: ['winter_market'],
    participatingPoiKeys: [
      'town_hall',
      'central_library',
      'study_cafe',
      'corner_shop',
      'city_park',
      'winter_market',
    ],
  },
  {
    eventKey: 'new_year_2027',
    name: 'Fresh Start Week',
    tabLabel: 'Ano Novo',
    emoji: '🎆',
    description: 'Réveillon na cidade: metas novas, vocabulário de resoluções e contratos curtos.',
    priority: 95,
    major: true,
    schedule: {
      type: 'fixed_annual',
      startMonth: 12,
      startDay: 27,
      endMonth: 1,
      endDay: 7,
    },
    vocabPackKey: 'christmas_2026',
    mapThemeKey: 'new_year',
    spiritLabel: 'Energia de ano novo',
    temporaryPoiKeys: [],
    participatingPoiKeys: ['town_hall', 'study_cafe', 'coworking_hub'],
  },
  {
    eventKey: 'halloween_2026',
    name: 'Spooky Study Nights',
    tabLabel: 'Halloween',
    emoji: '🎃',
    description: 'Halloween: vocabulário assustador, beco misterioso e desafios na biblioteca.',
    priority: 90,
    major: true,
    schedule: {
      type: 'fixed_annual',
      startMonth: 10,
      startDay: 20,
      endMonth: 11,
      endDay: 2,
    },
    vocabPackKey: 'christmas_2026',
    mapThemeKey: 'halloween',
    spiritLabel: 'Espírito assombrado',
    temporaryPoiKeys: ['spooky_alley'],
    participatingPoiKeys: ['central_library', 'city_park', 'spooky_alley', 'study_cafe'],
  },
  {
    eventKey: 'summer_fair',
    name: 'Summer Fair',
    tabLabel: 'Verão',
    emoji: '☀️',
    description: 'Feira de verão: inglês de viagem, praça ao ar livre e energia no parque.',
    priority: 80,
    major: false,
    schedule: {
      type: 'fixed_annual',
      startMonth: 7,
      startDay: 1,
      endMonth: 8,
      endDay: 31,
    },
    vocabPackKey: 'christmas_2026',
    mapThemeKey: 'summer',
    spiritLabel: 'Clima de verão',
    temporaryPoiKeys: ['summer_plaza'],
    participatingPoiKeys: ['city_park', 'study_cafe', 'summer_plaza', 'airport_gate'],
  },
];

export const CITY_EVENTS_BY_KEY = Object.fromEntries(
  CITY_EVENTS_CATALOG.map((event) => [event.eventKey, event]),
) as Record<string, CityEventDefinition>;
