export const HOME_UI = {
  screenTitle: 'English Quest',
  screenSubtitle: 'Seu mundo de evolução',
  zones: {
    now: {
      emoji: '⚡',
      title: 'Agora',
      subtitle: 'Identidade, streak e o que fazer hoje',
    },
    progress: {
      emoji: '📈',
      title: 'Progresso',
      subtitle: 'Metas do dia e próximas recompensas',
    },
    explore: {
      emoji: '🧭',
      title: 'Explorar',
      subtitle: 'Mundo vivo, atalhos e descobertas',
    },
  },
  playerHeader: {
    brand: 'Base do jogador',
    xpLabel: 'Experiência',
    prestigeLabel: 'Prestígio',
    coinsLabel: 'Moedas',
    studyPointsLabel: 'Pontos',
    studyPointsSuffix: 'SP',
    viewProfile: 'Ver perfil completo',
    editAvatar: 'Editar personagem',
    openProfile: 'Abrir perfil e identidade',
    viewProfileHint: 'Ver perfil →',
    xpProgress: (current: number, required: number, percent: number) =>
      `${current.toLocaleString('pt-BR')} / ${required.toLocaleString('pt-BR')} XP · ${percent}%`,
    xpRemaining: (remaining: number) =>
      `${remaining.toLocaleString('pt-BR')} XP para o próximo nível`,
  },
  activeObjectives: {
    title: 'Objetivos ativos',
    subtitle: (count: number) =>
      count === 1 ? '1 meta em andamento' : `${count} metas em andamento`,
    emptySubtitle: 'Tudo em dia por agora',
    emptyBody: 'Quando houver missões, rotinas ou recompensas pendentes, elas aparecem aqui.',
    emptyCta: 'Abrir Jogar',
    overflow: (count: number) =>
      count === 1 ? '+1 objetivo no Jogar' : `+${count} objetivos no Jogar`,
  },
  motivationSpark: {
    title: 'Chama de hoje',
    subtitle: 'Sua motivação pessoal',
    emptyTitle: 'Crie sua primeira faísca',
    emptyBody: 'Guarde frases, fotos ou áudios que te lembram por que você segue em frente.',
    createCta: 'Nova faísca',
    openCta: 'Acender agora',
    openHubCta: 'Abrir Chama Interior',
  },
  doNow: {
    title: 'Faça agora',
    cta: 'Fazer agora',
    viewQuests: 'Ver missões',
    empty: 'Suas missões diárias estão a caminho…',
    allDoneTitle: 'Missões do dia concluídas',
    allDoneBody: (count: number) =>
      count === 1
        ? 'Você completou 1 missão hoje. Continue evoluindo no jogo.'
        : `Você completou ${count} missões hoje. Continue evoluindo no jogo.`,
    missionHint: (pending: number) =>
      pending === 1 ? '1 missão pendente hoje' : `${pending} missões pendentes hoje`,
    rewardLine: (xp: number, coins: number) =>
      `+${xp} XP · +${coins.toLocaleString('pt-BR')} 🪙`,
  },
  quickActions: {
    title: 'Acesso rápido',
    hint: '6 atalhos principais — o restante fica no Menu',
    moreLabel: 'Mais',
    moreTagline: 'Menu completo',
    moreEmoji: '☰',
  },
  streak: {
    title: 'Sequência de estudo',
    current: 'Streak atual',
    best: 'Melhor streak',
    shields: 'Escudos',
    hintActive: 'Complete missões hoje para manter a chama acesa.',
    hintIdle: 'Faça uma missão para acender seu streak.',
  },
  pet: {
    title: 'Companheiro',
    emptyTitle: 'Seu companheiro te espera',
    emptyBody: 'Evolua no jogo para despertar seu primeiro pet.',
    emptyCta: 'Conhecer pets',
    energy: 'Energia',
    affinity: 'Afinidade',
    viewPet: 'Cuidar do pet',
  },
  dailyProgress: {
    title: 'Progresso de hoje',
    missions: 'Missões',
    routines: 'Rotinas',
    study: 'Atividade',
    xp: 'XP estimado',
    studyUnit: 'sessões',
  },
  quests: {
    title: 'Missões do dia',
    empty: 'Suas missões diárias estão a caminho…',
    viewAll: 'Ver todas',
    progressLabel: 'Progresso',
  },
  routines: {
    title: 'Rotina de hoje',
    viewAll: 'Gerenciar rotinas',
  },
  contract: {
    title: 'Contrato ativo',
    emptyTitle: 'Nenhum contrato',
    emptyBody: 'Aceite um desafio na cidade para apostar moedas e ganhar recompensas.',
    emptyCta: 'Explorar contratos',
    stake: 'Aposta',
    reward: 'Recompensa',
    risk: 'Risco',
    daysLeft: 'dias restantes',
  },
  vault: {
    title: 'Knowledge Vault',
    notes: 'Notas',
    reviews: 'Revisões',
    voice: 'Voice notes',
    level: 'Nível',
    openMap: 'Abrir Knowledge Map',
    emptyBody: 'Capture inglês real — voz, vocabulário e conexões.',
    emptyCta: 'Começar no Vault',
  },
  city: {
    title: 'Cidade internacional',
    nextEvolution: 'Próxima evolução',
    viewCity: 'Explorar cidade',
  },
  nextReward: {
    title: 'Próxima recompensa',
    levelUp: 'Subir de nível',
    lootBox: 'Caixa no inventário',
    petEgg: 'Ovo de pet',
    cityMilestone: 'Próximo marco urbano',
    prestige: 'Ascensão de prestígio',
    season: 'Recompensa de temporada',
  },
  events: {
    title: 'Eventos',
    comingSoon: 'Em breve',
    body: 'Quando houver evento na cidade ou temporada ativa, você verá aqui com dias restantes.',
    badge: 'Reservado',
    loading: 'Carregando eventos…',
    citySection: 'Evento na cidade',
    seasonSection: 'Temporada',
    viewCity: 'Ver na cidade',
    viewSeason: 'Ver temporada',
    tierLine: (tier: number, points: number) => `Tier ${tier} · ${points.toLocaleString('pt-BR')} pts`,
    claimable: (count: number) =>
      count === 1 ? '1 recompensa para resgatar' : `${count} recompensas para resgatar`,
    nextTier: (label: string) => `Próximo: ${label}`,
    spiritLine: (spirit: number, label: string) => `${label} · ${spirit}%`,
  },
  explore: {
    title: 'Mais modos',
    body: 'Carreira, farm, temporada, conquistas e tudo que não cabe na base.',
    cta: 'Abrir no perfil',
  },
} as const
