export const FLASH_DECK_UI = {
  screenTitle: 'Baralho Vivo',
  screenSubtitle: '1000 palavras essenciais + seus cadernos',
  starterDeckName: '1000 palavras essenciais',
  emoji: '📒',
  dueCount: (count: number) =>
    count === 0
      ? 'Nenhuma carta na mesa hoje'
      : count === 1
        ? '1 carta na mesa hoje'
        : `${count} cartas na mesa hoje`,
  dueHint: 'O Buddy guardou suas revisões para você',
  reviewCapReached: 'Você já revisou o máximo de cartas por hoje. Volte amanhã!',
  newCardLimitReached: (limit: number) =>
    `Limite de ${limit} cartas novas por dia. Revise as que já tem na mesa.`,
  startReview: 'Começar revisão',
  cardDuelCta: 'Duelo de cartas (5 due)',
  cardDuelHint: 'Treino na Arena sem gastar stamina',
  importCsv: 'Importar CSV',
  importCsvTitle: 'Importar cartas',
  importCsvHint: 'Formato: frente,verso,exemplo,tags (tags separadas por ;)',
  importCsvPick: 'Escolher arquivo .csv',
  importCsvSuccess: (imported: number, failed: number) =>
    `${imported} carta(s) importada(s)${failed > 0 ? ` · ${failed} falha(s)` : ''}`,
  mcqReview: 'Revisão MCQ',
  mcqReviewHint: 'Quiz rápido com alternativas',
  blitzReview: 'Blitz 2 min',
  blitzReviewHint: 'Revise o máximo de cartas em 2 minutos',
  blitzTimeLeft: (sec: number) => `${sec}s restantes`,
  blitzDone: (count: number) => `Blitz encerrado · ${count} revisões`,
  leechHelperTitle: 'Cartas preguiça',
  leechHelperBody: 'Muitos erros nestas palavras. Suspenda ou recomece o contador.',
  leechSuspend: 'Suspender',
  leechReset: 'Recomeçar',
  newCard: 'Nova carta',
  createTitle: 'Nova carta',
  createSubtitle: 'Anote uma palavra ou frase em inglês',
  frontLabel: 'Frente (inglês)',
  frontPlaceholder: 'Ex.: reluctant',
  backLabel: 'Verso (português)',
  backPlaceholder: 'Ex.: relutante',
  exampleLabel: 'Exemplo (opcional)',
  examplePlaceholder: 'She was reluctant to leave.',
  saveCard: 'Salvar carta',
  reviewTitle: 'Revisão',
  reviewEmpty: 'Tudo em dia! Volte mais tarde ou crie uma carta nova.',
  reviewProgress: (current: number, total: number) => `${current} de ${total}`,
  tapToFlip: 'Toque para ver o verso',
  tapToFlipBack: 'Toque para ver a frente',
  swipeHint: 'Toque para virar · arraste para classificar',
  swipeAfterFlip: '← reforjar · lembrei →',
  swipeLeftAgain: '← Reforjar',
  swipeRightGood: 'Lembrei →',
  swipeOrButtons: 'Ou use Quase / Fácil abaixo',
  againLabel: 'Reforjar',
  againHint: '~10 min',
  hardLabel: 'Quase',
  hardHint: 'Intervalo menor',
  goodLabel: 'Lembrei',
  goodHint: 'SM-2',
  easyLabel: 'Fácil!',
  easyHint: '+ intervalo',
  reviewDone: 'Revisão concluída!',
  reviewDoneBody: 'Suas cartas voltam na hora certa.',
  backToHub: 'Voltar ao baralho',
  statsTitle: 'Seu baralho',
  statsNew: 'Novas',
  statsLearning: 'Aprendendo',
  statsDue: 'Na mesa',
  statsMature: 'Maduras',
  statsLeech: 'Pregueiras',
  statsStreak: (days: number) =>
    days === 0 ? 'Sem sequência de tinta' : `Tinta fresca há ${days} dia${days === 1 ? '' : 's'}`,
  statsReviewsToday: (done: number, cap: number) => `${done}/${cap} revisões hoje`,
  statsNewToday: (done: number, limit: number) => `${done}/${limit} cartas novas hoje`,
  leechBanner:
    'Carta pregueira — essa palavra pede um truque de memória ou um exemplo mais pessoal.',
  stateLabels: {
    new: 'Nova',
    learning: 'Aprendendo',
    review: 'Revisão',
    relearning: 'Reforjando',
    mature: 'Madura',
  } as const,
  decksTitle: 'Meus cadernos',
  decksHint: 'Organize palavras por tema ou contexto',
  newDeck: 'Novo caderno',
  editDeck: 'Editar caderno',
  deckNameLabel: 'Nome do caderno',
  deckNamePlaceholder: 'Ex.: Viagem, Trabalho',
  deckEmojiLabel: 'Emoji da capa',
  deckDescriptionLabel: 'Descrição (opcional)',
  saveDeck: 'Salvar caderno',
  archiveDeck: 'Arquivar caderno',
  archiveDeckConfirm: 'Arquivar este caderno? As cartas permanecem salvas, mas o caderno some da lista.',
  deckEmptyTitle: 'Caderno vazio',
  deckEmptyBody: 'O Buddy está curioso — adicione a primeira carta ou importe palavras do farm.',
  hubEmptyDue: 'Nada na mesa agora. O Buddy está orgulhoso — volte mais tarde ou crie cartas novas.',
  searchPlaceholder: 'Buscar palavra, tradução ou tag…',
  tagsLabel: 'Tags (separadas por vírgula)',
  tagsPlaceholder: 'viagem, work, verbo',
  allTags: 'Todas',
  cardsInDeck: (count: number) => (count === 1 ? '1 carta' : `${count} cartas`),
  deckDueBadge: (count: number) => (count > 0 ? `${count} na mesa` : 'Em dia'),
  openDeck: 'Abrir caderno',
  editCard: 'Editar carta',
  deleteCard: 'Excluir carta',
  deleteCardConfirm: 'Excluir esta carta permanentemente?',
} as const;

export const FLASH_DECK_EMOJI_OPTIONS = ['📒', '✈️', '💼', '🎓', '🗣️', '🌍', '💡', '🔥', '📚', '🎯'] as const;
