export const MENTOR_AI_UI = {
  characterName: 'Professor Atlas',
  emoji: '🎓',
  home: {
    cardTitle: 'Professor Atlas',
    cardSubtitle: 'Seu mentor de inglês offline',
    openDashboard: 'Abrir mentor',
    weakestPreview: (skill: string) => `Foco: ${skill}`,
    recommendationPreview: (text: string) => text,
    offlineBadge: '100% no dispositivo',
  },
  voice: {
    startRecording: 'Gravar áudio para o Atlas',
    stopRecording: 'Parar gravação e enviar',
    send: 'Enviar mensagem',
    recording: 'Gravando',
    transcribing: 'Transcrevendo áudio…',
    translating: 'Traduzindo para inglês…',
    micPermissionDenied: 'Permita o microfone para praticar speaking com o Atlas.',
    recordingFailed: 'Não foi possível gravar o áudio. Tente novamente.',
    modeLabel: (mode: 'english' | 'portuguese_to_english') =>
      mode === 'english' ? 'Inglês direto' : 'PT → EN',
    modeA11y: (mode: 'english' | 'portuguese_to_english') =>
      mode === 'english'
        ? 'Modo de voz: inglês direto'
        : 'Modo de voz: português traduzido para inglês',
  },
  gpsStudy: {
    bannerTitle: 'Plano do GPS',
    bannerHint: 'Ao concluir a sessão, o Atlas credita progresso no GPS.',
    atlasLabel: 'Estudar com o Atlas',
  },
  dashboard: {
    title: 'Mentor IA',
    subtitle: 'Professor particular offline',
    heroSubtitle: (world: string, cefr: string, weakest: string) =>
      `Mundo ${world} (${cefr}) · reforço em ${weakest}`,
    levelChip: (level: number) => `Nv. ${level}`,
    streakChip: (days: number) => (days === 1 ? '🔥 1 dia' : `🔥 ${days} dias`),
    worldChip: (pct: number) => `GPS ${pct}%`,
    llmReady: 'Qwen 2.5 ativo',
    llmPreparing: 'Preparando modelo…',
    llmFallback: 'Motor pedagógico',
    greetingLabel: 'Saudação',
    skillsTitle: 'Suas habilidades',
    strongestLabel: 'Mais forte',
    weakestLabel: 'Mais fraca',
    recommendationTitle: 'Plano do Atlas',
    practiceTitle: 'Praticar agora',
    practiceHint: 'Tudo offline no seu dispositivo',
    goalsTitle: 'Metas do GPS',
    weeklyGoalTitle: 'Semana',
    monthlyGoalTitle: 'Mês',
    lastFeedbackTitle: 'Último feedback',
    shortcutsTitle: 'Atalhos',
    noWeeklyGoal: 'Siga o plano semanal do GPS.',
    noMonthlyGoal: 'Complete o checkpoint mensal para ver sua meta.',
    noFeedback: 'Corrija uma frase ou converse com o Atlas para ver feedback aqui.',
    engineNote: (label: string) => `Motor: ${label}`,
    memoryRecallTitle: 'O que o Atlas lembra',
    memoryRecallHint: 'Metas e preferências usadas para personalizar chat, correções e exercícios',
    memoryGoalsTitle: 'Objetivos',
    memoryPreferencesTitle: 'Preferências',
    memoryManageLabel: 'Gerenciar memória',
    gpsPathTitle: 'Trilha GPS',
    gpsWorldsChip: (count: number, target: string) =>
      count === 1 ? `1 mundo até ${target}` : `${count} mundos até ${target}`,
    gpsNextWorldChip: (name: string, cefr: string | null) =>
      cefr ? `Próximo: ${name} (${cefr})` : `Próximo: ${name}`,
    gpsSpeakingDayChip: '🗣️ Dia de conversação',
    gpsMissionLabel: 'Missão GPS',
    gpsOpenLabel: 'Ver GPS completo',
    farmBridgeTitle: 'Plano do GPS no Atlas',
    farmMinutesChip: (minutes: number) =>
      minutes === 0 ? '0 min no Farm hoje' : `${minutes} min no Farm hoje`,
    motivationBridgeTitle: 'Chama Interior',
    motivationStreakChip: (days: number) =>
      days === 1 ? '🔥 1 dia na Chama' : `🔥 ${days} dias na Chama`,
    motivationOpenedChip: 'Chama aberta hoje',
    motivationOpenSparkLabel: 'Abrir Chama de hoje',
    motivationOpenHubLabel: 'Ir para Chama Interior',
    ecosystemTitle: 'GPS · Farm · Chama',
    ecosystemHint: 'Atlas conecta trilha, prática e motivação',
    todayPlanTitle: 'Plano de hoje',
    todayPlanHint: 'Atlas lê mundo, skills, missões e metas do GPS em tempo real',
    gpsSyncTitle: 'Sincronizado com o GPS',
    gpsSyncBody:
      'Missões e unidades do GPS abrem direto no Atlas. Ao concluir exercício, chat ou roleplay, o progresso volta para o GPS.',
    progressTitle: 'Seu progresso',
    progressHint: 'Skills, metas e memória do Atlas',
    nextStepTitle: 'Próximo passo',
    moreActionsLabel: 'Outras ações',
    pathChip: (current: string, cefr: string, remaining: number, target: string) =>
      remaining <= 0
        ? `${current} (${cefr}) · ápice`
        : `${current} (${cefr}) · ${remaining} ${remaining === 1 ? 'mundo' : 'mundos'} → ${target}`,
  },
  chat: {
    title: 'Chat com o Atlas',
    subtitle: 'Pergunte qualquer coisa — 100% offline',
    inputPlaceholder: 'Digite ou grave áudio (🎙️)…',
    inputA11y: 'Mensagem para o Professor Atlas',
    send: 'Enviar',
    cancel: 'Cancelar',
    cancelAction: 'Cancelar',
    messageActionsTitle: 'Mensagem',
    copyMessage: 'Copiar',
    copyHint: 'Segure para copiar a mensagem',
    thinking: 'Atlas está pensando…',
    newSession: 'Nova conversa',
    offlineBadge: '100% offline',
    llmReady: 'Qwen 2.5 local ativo',
    llmPreparing: 'Preparando modelo…',
    llmFallback: 'Motor pedagógico (fallback)',
    suggestions: [
      'Como se fala "hoje eu vou buscar minha esposa"?',
      'Explain Present Perfect',
      'Correct this: "I have 30 years old"',
    ],
    goalCapturedNote: (goal: string) => `🎯 Objetivo salvo na memória do Atlas: “${goal}”`,
  },
  correct: {
    title: 'Correção de frases',
    subtitle: 'Envie uma frase — receba ❌ ✅ 💡',
    intro:
      'Cole ou digite uma frase em inglês. O Atlas devolve erro, correção e explicação curta — tudo offline.',
    offlineEngine: 'Motor pedagógico offline',
    inputLabel: 'Sua frase',
    inputPlaceholder: 'Ex.: I have 30 years old',
    inputA11y: 'Frase em inglês para correção',
    submit: 'Corrigir frase',
    cancel: 'Cancelar',
    thinking: 'Atlas está analisando…',
    wrongLabel: 'Como você escreveu',
    rightLabel: 'Forma correta',
    tipLabel: 'Explicação',
    tipLabelEn: 'Explanation (EN)',
    tipLabelPt: 'Explicação (PT)',
    practiceLabel: 'Dica de prática',
    share: 'Compartilhar',
    shareTitle: 'Correção do Professor Atlas',
    practiceAnother: 'Corrigir outra',
    savedNote: 'Salvo no seu histórico de erros frequentes.',
    examplesTitle: 'Exemplos rápidos',
    examples: [
      'I have 30 years old',
      'I am agree with you',
      'I have been to there',
      'I have a doubt about this',
    ],
  },
  exercise: {
    title: 'Exercícios e flashcards',
    subtitle: 'Gere quiz e cartas — 100% offline',
    intro:
      'Peça exercícios de múltipla escolha ou flashcards sobre qualquer tema. Faça o quiz aqui ou salve as cartas no Baralho Vivo.',
    offlineEngine: 'Motor pedagógico offline',
    tabs: {
      exercise: 'Exercícios',
      flashcards: 'Flashcards',
    },
    topicLabel: 'Tema',
    topicPlaceholder: 'Ex.: Past Simple, travel, APIs',
    topicA11y: 'Tema dos exercícios',
    generate: 'Gerar exercícios',
    cancel: 'Cancelar',
    thinking: 'Atlas está montando o quiz…',
    previewTitle: 'Preview do quiz',
    previewCount: (count: number) => `${count} perguntas prontas`,
    startSession: 'Fazer exercício',
    generateAnother: 'Gerar outro tema',
    confirm: 'Confirmar resposta',
    next: 'Próxima pergunta',
    finish: 'Ver resultado',
    correct: 'Correto!',
    incorrect: 'Quase! Veja a explicação:',
    resultTitle: 'Quiz concluído!',
    resultBody: (correct: number, total: number, pct: number) =>
      `Você acertou ${correct} de ${total} (${pct}%).`,
    generatingFeedback: 'Atlas está analisando seus erros…',
    weaknessesTitle: 'Onde você errou',
    improvementsTitle: 'O que melhorar',
    tryAnother: 'Novo tema',
    backToPreview: 'Voltar ao preview',
    examplesTitle: 'Temas rápidos',
    examples: ['Past Simple', 'Present Perfect', 'Travel vocabulary'],
  },
  flashcards: {
    topicLabel: 'Tema dos flashcards',
    topicPlaceholder: 'Ex.: travel, interview tech',
    topicA11y: 'Tema dos flashcards',
    countHint: 'Gera 10 cartas por padrão (5–20).',
    generate: 'Gerar flashcards',
    cancel: 'Cancelar',
    thinking: 'Atlas está criando as cartas…',
    previewTitle: 'Preview das cartas',
    previewCount: (count: number) => `${count} cartas geradas`,
    tapToOpen: 'Toque em uma carta para abrir com flip, igual ao Baralho Vivo.',
    startStudy: 'Abrir cartas',
    openCard: 'Abrir carta',
    prevCard: 'Anterior',
    nextCard: 'Próxima',
    finishStudy: 'Concluir',
    backToList: 'Voltar à lista',
    openInDeck: 'Revisar no Baralho Vivo',
    export: 'Salvar no Baralho Vivo',
    exporting: 'Salvando…',
    savedNote: (count: number) => `${count} cartas salvas no Baralho Vivo.`,
    generateAnother: 'Gerar outro tema',
    examplesTitle: 'Temas rápidos',
    examples: ['Travel', 'Interview tech', 'Daily vocabulary'],
  },
  shortcuts: {
    chat: {
      label: 'Chat livre',
      emoji: '💬',
      route: '/mentor/chat',
      description: 'Pergunte sobre gramática, vocabulário ou tradução',
    },
    correct: {
      label: 'Corrigir frase',
      emoji: '✏️',
      route: '/mentor/correct',
      description: 'Envie uma frase e receba ❌ ✅ 💡',
    },
    exercise: {
      label: 'Exercícios',
      emoji: '📝',
      route: '/mentor/exercise',
      description: 'Quiz com feedback + flashcards',
    },
    roleplay: {
      label: 'Roleplay',
      emoji: '🎭',
      route: '/mentor/roleplay',
      description: 'Conversação e entrevistas técnicas',
    },
    history: {
      label: 'Histórico e memória',
      emoji: '📜',
      route: '/mentor/history',
      description: 'Conversas, correções e o que o Atlas lembra',
    },
    settings: {
      label: 'Configurações',
      emoji: '⚙️',
      route: '/mentor/settings',
      description: 'Status do modelo e APK com Qwen',
    },
  },
  roleplay: {
    title: 'Roleplay e entrevistas',
    subtitle: 'Pratique speaking com cenários reais — 100% offline',
    intro:
      'Escolha um papel para Conversation Practice ou uma trilha de entrevista técnica. O Atlas responde em personagem e avalia suas respostas ao final.',
    offlineEngine: 'Motor pedagógico offline',
    tabs: {
      conversation: 'Conversação',
      interview: 'Entrevista',
    },
    pickRole: 'Escolha o papel',
    pickTrack: 'Escolha a trilha',
    inputPlaceholder: 'Fale ou digite — PT vira inglês automaticamente',
    inputA11y: 'Sua resposta no roleplay',
    finish: 'Encerrar',
    generatingFeedback: 'Gerando feedback…',
    turnsProgress: (current: number, min: number) =>
      `${current} turno${current === 1 ? '' : 's'} · meta ${min}+`,
    feedbackTitle: 'Feedback por competência',
    nextStepsTitle: 'Próximos passos',
    newSession: 'Nova simulação',
    competencies: {
      clarity: 'Clareza',
      vocabulary: 'Vocabulário',
      grammar: 'Gramática',
      technical: 'Vocabulário técnico',
    },
  },
  history: {
    title: 'Histórico e memória',
    subtitle: 'Conversas, correções e contexto do Atlas',
    intro:
      'Tudo fica no seu dispositivo. O Atlas usa esses dados para personalizar correções, exercícios e o chat.',
    tabs: {
      chats: '💬 Conversas',
      errors: '✏️ Correções',
      memory: '🧠 Memória',
    },
    emptyChatsTitle: 'Nenhuma conversa ainda',
    emptyChatsBody: 'Converse com o Atlas no chat livre para ver o histórico aqui.',
    emptyChatPreview: 'Conversa iniciada',
    emptyErrorsTitle: 'Nenhuma correção salva',
    emptyErrorsBody: 'Use “Corrigir frase” para registrar erros frequentes.',
    emptyMemorySection: 'Nada registrado ainda.',
    messageCount: (count: number) =>
      count === 0 ? 'Sem mensagens suas' : `${count} mensagem${count === 1 ? '' : 's'} sua${count === 1 ? '' : 's'}`,
    openChat: 'Continuar conversa',
    deleteChat: 'Apagar',
    deleteChatTitle: 'Apagar conversa?',
    deleteChatBody: (title: string) => `“${title}” será removida deste dispositivo.`,
    deleteError: 'Remover',
    deleteErrorTitle: 'Remover correção?',
    deleteErrorBody: 'Este registro sai do histórico de erros frequentes.',
    deleteMemoryTitle: 'Remover da memória?',
    deleteMemoryBody: 'O Atlas deixará de usar este dado no contexto.',
    deleteEntry: 'Remover entrada',
    deleteConfirm: 'Remover',
    cancel: 'Cancelar',
    youLabel: 'Você',
    atlasLabel: 'Atlas',
    frequentErrorsTitle: 'Erros mais frequentes',
    practiceErrors: 'Praticar meus erros',
    practiceErrorsHint: 'Gera um quiz MCQ focado nas suas correções salvas',
    practiceErrorsLoading: 'Montando quiz…',
    practiceErrorsEmpty: 'Corrija frases primeiro para gerar um quiz personalizado.',
    goalsTitle: 'Objetivos',
    goalsHint: 'O que você quer alcançar com o inglês',
    goalPlaceholder: 'Ex.: conseguir vaga internacional',
    goalSuggestions: [
      'Conseguir vaga internacional',
      'Melhorar speaking para reuniões',
      'Passar em entrevista frontend',
    ],
    preferencesTitle: 'Preferências',
    preferencesHint: 'Tom e áreas de foco do Atlas',
    preferencePlaceholder: 'Ex.: React, tom casual',
    preferenceSuggestions: ['Frontend / React', 'Mobile', 'Tom mais formal', 'Tom mais casual'],
    topicsTitle: 'Temas estudados',
    topicsHint: 'Salvos automaticamente a partir do chat',
    addEntry: 'Adicionar',
    errorCategories: {
      grammar_tense: 'Tempos verbais',
      grammar_agreement: 'Concordância',
      vocabulary: 'Vocabulário',
      preposition: 'Preposições',
      article: 'Artigos',
      word_order: 'Ordem das palavras',
      collocation: 'Colocação',
      other: 'Outros',
    },
  },
  settings: {
    title: 'Configurações',
    subtitle: 'Modelo, motor e privacidade',
    engineTitle: 'Motor do Atlas',
    modelTitle: 'Modelo embutido',
    modelNameLabel: 'Nome',
    modelFileLabel: 'Arquivo',
    modelSizeLabel: 'Tamanho',
    modelSourceLabel: 'Origem',
    modelPathLabel: 'Caminho local',
    nativeActive: 'LLM nativo',
    pedagogyActive: 'Motor pedagógico',
    platformChip: (os: string) => os === 'android' ? 'Android' : os,
    statusReady: 'Qwen pronto',
    statusReadyHint: 'O modelo está carregado e o chat usa inferência local.',
    statusCopying: 'Copiando modelo',
    statusCopyingHint: 'Extraindo o GGUF do APK para o armazenamento interno (~1 GB).',
    statusLoading: 'Carregando na memória',
    statusLoadingHint: 'Aguarde — a primeira carga pode levar até 1 minuto.',
    statusMissing: 'Modelo ausente',
    statusMissingHint: 'O APK foi gerado sem o arquivo GGUF embutido.',
    statusError: 'Falha ao carregar',
    statusErrorHint: 'Verifique espaço livre (~2 GB) e tente recarregar.',
    statusUnsupported: 'Não suportado',
    statusUnsupportedHint: 'LLM nativo funciona no Android com APK release.',
    statusIdle: 'Aguardando',
    statusIdleHint: 'O modelo ainda não foi inicializado nesta sessão.',
    retryLoad: 'Tentar carregar novamente',
    retryLoading: 'Carregando…',
    privacyTitle: 'Privacidade e dados',
    privacyHint: 'Tudo fica no seu dispositivo — nada vai para a nuvem',
    retentionTitle: 'Limpeza automática',
    retentionHint: 'Remove conversas, correções e temas antigos. Objetivos e preferências são mantidos.',
    retentionDisabled: 'Desativada',
    retentionDaysLabel: (days: number) => `${days} dias`,
    retentionRunNow: 'Executar limpeza agora',
    retentionRunning: 'Limpando…',
    retentionLastRun: (summary: string) => `Última limpeza: ${summary}`,
    retentionNothingRemoved: 'nada removido',
    retentionRemovedSummary: (chats: number, errors: number, topics: number) => {
      const parts: string[] = []
      if (chats > 0) parts.push(`${chats} conversa${chats === 1 ? '' : 's'}`)
      if (errors > 0) parts.push(`${errors} correção${errors === 1 ? '' : 'es'}`)
      if (topics > 0) parts.push(`${topics} tema${topics === 1 ? '' : 's'}`)
      return parts.length > 0 ? parts.join(', ') + ' removidos' : 'nada removido'
    },
    statChats: 'Conversas',
    statErrors: 'Correções',
    statMemory: 'Memórias',
    clearChats: 'Apagar histórico de chat',
    clearChatsTitle: 'Apagar conversas?',
    clearChatsBody: 'Todas as sessões de chat com o Atlas serão removidas deste dispositivo.',
    clearAll: 'Apagar todos os dados do Mentor',
    clearAllTitle: 'Apagar tudo do Mentor?',
    clearAllBody:
      'Remove conversas, correções salvas e memória do Atlas. Esta ação não pode ser desfeita.',
    clearConfirm: 'Apagar',
    cancel: 'Cancelar',
    devTitle: 'Para desenvolvedores',
    devIntro: 'Gere um APK release com o modelo embutido:',
    devSteps: [
      'pnpm run mentor:download-model',
      'pnpm run android:apk:release',
      'pnpm run android:install:release',
    ],
    footerNote: 'Professor Atlas — 100% offline. Seus dados nunca saem do dispositivo.',
  },
  stubs: {
    backToDashboard: 'Voltar ao dashboard',
  },
} as const
