export const MOTIVATION_UI = {
  hub: {
    title: 'Chama Interior',
    subtitle: 'Suas faíscas de motivação pessoal',
    emoji: '🔥',
    tagline: 'Cofre pessoal',
    heroTitle: 'Acenda quando precisar',
    heroBody: 'Guarde o que te move. Nos dias difíceis, sua chama volta a brilhar.',
    statsSparks: (count: number) => (count === 1 ? '1 faísca' : `${count} faíscas`),
    statsWithMedia: (count: number) => (count === 1 ? '1 com mídia' : `${count} com mídia`),
    statsPinned: (count: number) => (count === 1 ? '1 fixada' : `${count} fixadas`),
    dailySectionTitle: 'Chama de hoje',
    dailySectionSubtitle: 'A faísca escolhida para te lembrar do porquê',
    dailyOpenCta: 'Acender agora',
    librarySectionTitle: 'Suas faíscas',
    librarySectionSubtitle: 'Tudo que você guardou para si',
    emptyTitle: 'Nenhuma faísca ainda',
    emptySubtitle: 'Guarde o que te move — uma frase, foto ou lembrete só seu.',
    createCta: 'Nova faísca',
    searchPlaceholder: 'Buscar faíscas…',
    filterAll: 'Todas',
    filterFavorites: 'Favoritas',
    filterPinned: 'Fixadas',
    filterArchived: 'Arquivadas',
    archivedCta: 'Ver arquivadas',
    allArchivedTitle: 'Todas as faíscas estão arquivadas',
    allArchivedBody: 'Elas continuam salvas — use o filtro Arquivadas para restaurar.',
    collectionsCta: 'Coleções',
    openStreak: (days: number) => (days === 1 ? '1 dia aceso' : `${days} dias acesos`),
  },
  collections: {
    title: 'Coleções',
    subtitle: 'Organize suas faíscas por tema',
    emoji: '📁',
    emptyTitle: 'Nenhuma coleção ainda',
    emptyBody: 'Agrupe faíscas por carreira, família, inglês…',
    createCta: 'Nova coleção',
    namePlaceholder: 'Nome da coleção',
    emojiLabel: 'Emoji',
    deleteCta: 'Excluir coleção',
    sparksCount: (count: number) => (count === 1 ? '1 faísca' : `${count} faíscas`),
  },
  create: {
    title: 'Nova faísca',
    subtitle: 'Texto, imagens, áudio ou links — tudo fica só no seu aparelho',
  },
  detail: {
    title: 'Sua faísca',
    messageSection: 'Mensagem',
    voiceSection: 'Sua voz',
    linksSection: 'Inspirações',
    pinnedBadge: 'Fixada',
    favoriteBadge: 'Favorita',
    pinCta: 'Fixar',
    unpinCta: 'Desafixar',
    favoriteCta: 'Favoritar',
    unfavoriteCta: 'Remover favorito',
    editCta: 'Editar',
    archiveCta: 'Arquivar',
    unarchiveCta: 'Desarquivar',
    archivedBadge: 'Arquivada',
    archivedBanner: 'Fora da rotação diária — só você ainda vê aqui.',
    deleteCta: 'Excluir',
    notFound: 'Faísca não encontrada.',
  },
  archived: {
    title: 'Arquivadas',
    subtitle: 'Guardadas, mas fora da chama diária',
    emoji: '📦',
    emptyTitle: 'Nenhuma faísca arquivada',
    emptyBody: 'Ao arquivar, a faísca some da lista e da rotação — mas continua salva aqui.',
    restoreCta: 'Desarquivar',
  },
  notifications: {
    morningAudioBody: '🎙️ Você gravou isso para si. Toque para ouvir sua mensagem.',
    eveningAudioBody: '🎙️ Sua voz te espera. Um minuto só para você.',
    morningImageBody: '📷 Uma lembrança visual do seu porquê. Toque para ver.',
    eveningImageBody: '📷 Reveja a imagem que te impulsiona. Toque para abrir.',
    morningFallbackBody: (title: string) => `Acenda sua chama: ${title}`,
    eveningFallbackBody: (title: string) => `Antes de descansar — ${title}`,
    openCta: 'Acender agora →',
  },
  settings: {
    title: 'Configurações',
    subtitle: 'Horários e lembretes da Chama Interior',
    emoji: '⚙️',
    sectionTitle: 'Chama Interior',
    sectionBody: 'Lembretes com suas próprias faíscas — só no seu aparelho.',
    enabledLabel: 'Ativar Chama Interior',
    enabledHint: 'Desliga lembretes e card na Home',
    dailyNotificationLabel: 'Lembrete diário',
    dailyNotificationHint: 'Uma notificação por dia com a faísca escolhida',
    showOnHomeLabel: 'Card na Home',
    showOnHomeHint: 'Mostra a chama de hoje na tela inicial',
    eveningNotificationLabel: 'Última chama do dia',
    eveningNotificationHint: 'Segundo lembrete no fim do dia com a mesma faísca',
    eveningTimeLabel: 'Horário da noite',
    preferredTimeLabel: 'Horário da chama',
    exportMediaCta: 'Exportar mídia',
    exportMediaHint: 'Gera um pacote ZIP com fotos e áudios das faíscas',
    avoidRepeatLabel: 'Evitar repetir',
    avoidRepeatHint: 'Dias sem repetir a mesma faísca na rotação',
    avoidRepeatDays: (days: number) => (days === 1 ? '1 dia' : `${days} dias`),
    globalNotificationsHint:
      'O toggle global “Chama Interior” no Perfil também precisa estar ativo para receber lembretes.',
    backupHint:
      'Faíscas entram no backup JSON do jogo. Fotos e áudios ficam no aparelho — copie o backup junto com os arquivos se trocar de celular.',
  },
  form: {
    titleLabel: 'Título',
    titlePlaceholder: 'Ex.: Por que estudo inglês',
    bodyLabel: 'Mensagem',
    bodyPlaceholder: 'Escreva o que você quer lembrar nos dias difíceis…',
    saveCta: 'Salvar faísca',
    imagesLabel: 'Imagens',
    imagesHint: (max: number) => `Até ${max} fotos — câmera ou galeria`,
    imagesAttachedCount: (count: number, max: number) => `${count}/${max} anexadas`,
    imagesLimitReached: (max: number) => `Limite de ${max} imagens atingido.`,
    imagesPermissionDenied: 'Permita acesso às fotos ou câmera nas configurações do aparelho.',
    takePhoto: 'Tirar foto',
    pickImage: 'Galeria',
    audioLabel: 'Áudio',
    audioHint: 'Grave uma mensagem para ouvir nos dias difíceis',
    importAudio: 'Importar áudio',
    removeAudio: 'Remover áudio',
    replaceAudio: 'Substituir áudio',
    micPermissionDenied: 'Permita o microfone nas configurações do aparelho.',
    recordVoice: 'Gravar mensagem',
    recordingHint: 'Toque em gravar e fale com você mesmo',
    pauseRecording: 'Pausar',
    resumeRecording: 'Continuar',
    finishRecording: 'Concluir',
    deleteRecording: 'Apagar gravação',
    collectionLabel: 'Coleção',
    collectionNone: 'Sem coleção',
    linksLabel: 'Links',
    linksHint: 'Talks, vídeos ou artigos que te inspiram',
    linkUrlPlaceholder: 'https://…',
    linkTitlePlaceholder: 'Título opcional',
    addLink: 'Adicionar link',
    removeLink: 'Remover link',
    openLink: 'Abrir link',
  },
} as const
