export const MOTIVATION_MAX_TITLE_LENGTH = 120
export const MOTIVATION_MAX_BODY_LENGTH = 4000
export const MOTIVATION_MAX_IMAGES_PER_SPARK = 5
export const MOTIVATION_MAX_LINKS_PER_SPARK = 3
export const MOTIVATION_MAX_AUDIO_DURATION_MS = 3 * 60 * 1000
export const MOTIVATION_MAX_ACTIVE_SPARKS = 200
export const MOTIVATION_SOFT_WARNING_SPARKS = 150
