export const LEARNING_GPS_UI = {
  home: {
    cardTitle: 'GPS do inglês',
    cardSubtitle: 'Sua trilha A1 → C2',
    openGps: 'Abrir GPS',
    nextStepPreview: (title: string) => `Próximo: ${title}`,
    todayDone: 'Plano de hoje concluído',
    todayPending: (count: number) =>
      count === 1 ? '1 pendência hoje' : `${count} pendências hoje`,
    whereTitle: 'Onde estou',
    whereSubtitle: 'Seu mundo e nível CEFR',
    todayTitle: 'Estudar hoje',
    todaySubtitle: (minutes: number) => `${minutes} min planejados`,
    viewTrail: 'Ver trilha completa',
    worldProgress: (percent: number) => `${percent}% do mundo atual`,
    cefrLabel: (level: string) => `Nível ${level}`,
    blocksEmpty: 'Configure seu ritmo no onboarding para ver o plano do dia.',
    blocksProgress: (done: number, total: number) => `${done}/${total} blocos concluídos`,
    goToFarm: 'Estudar no Farm',
    studyWithAtlas: 'Estudar com o Atlas',
    markDone: 'Marcar feito',
    blockCompleted: 'Concluído',
    blockProgress: (current: number, target: number) => `${current}/${target} min`,
    routinesTitle: 'Suas rotinas',
    routinesSubtitle: (done: number, total: number) =>
      total === 0 ? 'Nenhuma rotina hoje' : `${done}/${total} rotinas concluídas`,
    routinesEmpty: 'Cadastre rotinas fixas (aula, conversação, podcast…) para aparecerem aqui.',
    manageRoutines: 'Gerenciar rotinas',
    routineCompleted: 'Concluída',
    routinePending: 'Pendente',
    routineComplete: 'Concluir',
    routineUncomplete: 'Desmarcar',
  },
  tabs: {
    today: 'Hoje',
    trail: 'Trilha',
    insights: 'Insights',
  },
  screen: {
    title: 'GPS do inglês',
    subtitle: 'O que estudar agora',
    emoji: '🧭',
    nextStepTitle: 'Próximo passo',
    nextStepDone: 'Tudo feito por hoje',
    todayProgress: (blocksDone: number, blocksTotal: number, routinesDone: number, routinesTotal: number) => {
      const parts: string[] = []
      if (blocksTotal > 0) parts.push(`${blocksDone}/${blocksTotal} blocos`)
      if (routinesTotal > 0) parts.push(`${routinesDone}/${routinesTotal} rotinas`)
      return parts.length > 0 ? parts.join(' · ') : 'Nada pendente'
    },
    expandUnits: (count: number) => `Ver todas (${count})`,
    collapseUnits: 'Mostrar menos',
    completedUnits: (count: number) => `${count} concluída${count === 1 ? '' : 's'}`,
    lockedUnits: (count: number) => `${count} bloqueada${count === 1 ? '' : 's'}`,
    worldsStepperHint: 'Toque em um mundo para ver a meta',
    showWeeklyPlan: 'Ver plano completo da semana',
    hideWeeklyPlan: 'Ocultar plano da semana',
    showMonthlyReport: 'Ver relatório completo',
    hideMonthlyReport: 'Ocultar relatório',
    skillsTitle: 'Suas habilidades',
    skillsSubtitle: '0 a 100 em cada área',
    todayTitle: 'Plano de hoje',
    worldsTitle: 'Mundos',
    worldsSubtitle: 'Evolua completando cada fase',
    lockedWorld: 'Complete o mundo anterior para desbloquear',
    currentWorldBadge: 'Mundo atual',
    curriculumTitle: (worldName: string) => `Currículo ${worldName}`,
    curriculumSubtitle: (done: number, total: number) => `${done}/${total} unidades`,
    worldCompletedBadge: 'Concluído',
    unitLocked: 'Complete a unidade anterior',
    unitPractice: (current: number, target: number) => `${current}/${target}`,
    unitCompleted: 'Concluída',
    practiceCta: 'Praticar',
    markUnitDone: 'Marcar concluída',
    worldAdvanced: (worldName: string) => `Novo mundo desbloqueado: ${worldName}!`,
    intelligenceTitle: 'Seu coach de inglês',
    intelligenceSubtitle: 'Fraquezas, missões e plano da semana',
    weaknessesTitle: 'Pontos de atenção',
    weaknessesEmpty: 'Perfil equilibrado — continue o ritmo atual.',
    weaknessGap: (gap: number) => `${gap}% abaixo da média`,
    missionsTitle: 'Missões para você',
    missionsEmpty: 'Complete blocos do dia e unidades do currículo para novas missões.',
    weeklyTitle: 'Plano da semana',
    weeklyToday: 'Foco de hoje',
    weeklyProjectTitle: 'Projeto semanal',
    weeklyReviewDay: 'Dia de revisão',
    weeklySpeakingDay: 'Speaking Day',
    monthlyTitle: 'Relatório do mês',
    monthlyGenerated: (monthKey: string) => `Checkpoint ${monthKey}`,
    monthlyGoalsTitle: 'Próximos objetivos',
    priorityFocus: 'Foco prioritário',
    missionSource: {
      weakness: 'Gap detectado',
      world: 'Mundo atual',
      routine: 'Rotina',
    },
  },
  unitKind: {
    vocabulary: 'Vocabulário',
    grammar: 'Gramática',
    speaking: 'Conversação',
    checkpoint: 'Checkpoint',
  },
  onboarding: {
    worldTitle: 'Por onde começar?',
    worldSubtitle: 'Novos jogadores iniciam no Survivor (A1). Os outros mundos desbloqueiam conforme você evolui.',
    survivorHint: 'Recomendado para começar do zero',
  },
} as const
