import type { JournalCategoryValue, JournalEntryTypeValue, JournalImportanceValue } from '@/types/journal';

export const JOURNAL_UI = {
  screenTitle: 'English Knowledge Vault',
  screenSubtitle: 'My English Brain — seu second brain de inglês',
  emptyLibrary: 'Nenhuma nota ainda. Registre sua primeira descoberta.',
  addEntry: 'Nova nota',
  editEntry: 'Editar nota',
  favorites: 'Favoritos',
  dueReview: 'Para revisar',
  recent: 'Recentes',
  important: 'Mais importantes',
  searchPlaceholder: 'Buscar título, tags ou texto…',
  allCategories: 'Todas',
  allTypes: 'Todos os tipos',
  allImportance: 'Todas',
  favorite: 'Favorito',
  unfavorite: 'Remover favorito',
  archive: 'Arquivar',
  delete: 'Excluir',
  deleteNoteTitle: 'Excluir nota',
  deleteNoteConfirm: 'Esta nota será apagada permanentemente, incluindo o áudio gravado.',
  deleteNoteAction: 'Excluir',
  optionalAudioLabel: 'Áudio opcional',
  optionalAudioHint: 'Grave uma explicação em inglês — útil mesmo em notas de texto',
  replaceAudio: 'Substituir gravação',
  removeAudio: 'Remover áudio',
  voiceNoteAudioRequired: 'Grave um áudio antes de salvar a nota de voz',
  reviewNow: 'Revisar agora',
  listenAgain: 'Ouvir gravação',
  playPlayback: 'Reproduzir áudio',
  pausePlayback: 'Pausar áudio',
  seekPlayback: 'Posição do áudio — toque para avançar ou voltar',
  voiceNoteLabel: 'Gravação de voz',
  voiceStatusPlaying: 'Reproduzindo',
  voiceStatusPaused: 'Pausado',
  voiceStatusIdle: 'Toque para ouvir',
  voiceTimeOf: (current: string, total: string) => `${current} / ${total}`,
  statsTitle: 'Biblioteca de conhecimento',
  knowledgeProgress: (n: number) => `${n} pontos de conhecimento na cidade`,
  recordVoice: 'Gravar nota de voz',
  pauseRecording: 'Pausar',
  resumeRecording: 'Retomar',
  finishRecording: 'Finalizar gravação',
  playRecording: 'Reproduzir',
  deleteRecording: 'Excluir áudio',
  recordingHint: 'Grave explicações, correções ou insights em inglês',
  transcriptionHint: 'Ao finalizar a gravação, o conteúdo da nota é preenchido automaticamente.',
  transcriptionModeLabel: 'Idioma da gravação',
  transcriptionModeEnglish: 'Inglês direto',
  transcriptionModePortuguese: 'Português → inglês',
  transcriptionModeEnglishHint: 'Fale em inglês; o texto vai para o conteúdo como você disse.',
  transcriptionModePortugueseHint:
    'Fale em português; transcrevemos e traduzimos para inglês no conteúdo da nota.',
  transcribing: 'Transcrevendo áudio…',
  transcribingPortuguese: 'Transcrevendo em português…',
  translatingToEnglish: 'Traduzindo para inglês…',
  originalPortugueseLabel: 'Original (PT)',
  translationUnavailable:
    'Tradução offline indisponível. Recompile o app com fast-mlkit-translate-text (pnpm android / pnpm ios).',
  translationFailed: 'Não foi possível traduzir para inglês. O texto em português não foi salvo.',
  translationToPortugueseFailed: 'Não foi possível traduzir para português.',
  translationEmpty: 'Nada para traduzir após a transcrição.',
  viewInPortuguese: 'Ver em português',
  hidePortugueseTranslation: 'Ocultar tradução',
  translatingToPortuguese: 'Traduzindo para português…',
  portugueseTranslationLabel: 'Tradução (PT-BR)',
  transcriptionUnavailable:
    'Transcrição indisponível. Recompile o app com expo-speech-recognition (pnpm android / pnpm ios).',
  transcriptionPermissionDenied:
    'Permissão de reconhecimento de fala negada. Ative nas configurações do aparelho.',
  transcriptionEmpty:
    'Não foi possível detectar fala no áudio. Grave de novo, fale perto do microfone e evite silêncio longo no início.',
  transcriptionLanguageUnavailable:
    'Idioma de voz não disponível no aparelho. Instale o pacote de voz em Configurações → Sistema → Idiomas.',
  transcriptionFailed: 'Não foi possível transcrever o áudio. Você pode digitar o conteúdo manualmente.',
  titleLabel: 'Título',
  titleHint: 'Obrigatório — como você vai encontrar depois',
  titlePlaceholder: 'Ex.: Although vs even though',
  bodyLabel: 'Conteúdo',
  bodyHint: 'Texto da nota, frase ou resumo',
  bodyPlaceholder: 'Escreva o que aprendeu…',
  tagsLabel: 'Tags',
  tagsHint: 'Separadas por espaço — ex.: grammar past-tense',
  tagsPlaceholder: 'grammar speaking',
  categoryLabel: 'Categoria',
  typeLabel: 'Tipo de registro',
  importanceLabel: 'Prioridade',
  importanceHint: 'Toque no nível — de referência até urgente',
  save: 'Salvar no journal',
  cancel: 'Cancelar',
  xpEarned: (xp: number) => `+${xp} XP`,
  reviewBanner: (count: number) =>
    count === 1 ? '1 nota pronta para revisão' : `${count} notas prontas para revisão`,
  micPermissionDenied: 'Permissão de microfone negada. Ative nas configurações do aparelho.',
} as const;

export const JOURNAL_ENTRY_TYPE_LABELS: Record<JournalEntryTypeValue, string> = {
  voice_note: 'Nota de voz',
  text_note: 'Nota de texto',
  quick_note: 'Nota rápida',
  lesson_summary: 'Resumo de aula',
  teacher_feedback: 'Feedback do professor',
  interview_notes: 'Notas de entrevista',
  interview_note: 'Nota de entrevista',
  programming_english: 'Inglês técnico',
  vocabulary_entry: 'Entrada de vocabulário',
  grammar_entry: 'Regra de gramática',
  programming_concept: 'Conceito técnico',
};

export const JOURNAL_CATEGORY_LABELS: Record<JournalCategoryValue, string> = {
  vocabulary: 'Vocabulário',
  grammar: 'Gramática',
  speaking: 'Speaking',
  listening: 'Listening',
  reading: 'Leitura',
  writing: 'Escrita',
  interview: 'Entrevista',
  career: 'Carreira',
  programming_english: 'Programação',
  personal: 'Pessoal',
};

export const JOURNAL_IMPORTANCE_LABELS: Record<JournalImportanceValue, string> = {
  low: 'Baixa',
  medium: 'Média',
  high: 'Alta',
  critical: 'Crítica',
};

export const JOURNAL_REVIEW_MESSAGES: Record<number, string> = {
  1: 'Review this note again.',
  2: 'Do you still remember this?',
  3: "Let's reinforce this knowledge.",
  4: 'Long-term memory review.',
};
