export const GRAPH_UI = {
  title: 'Mapa de conhecimento',
  subtitle: 'Seu inglês organizado por áreas',
  intro: 'Cada área é um ramo. Toque em uma nota para ver vínculos e abrir.',
  filterSpace: 'Área',
  filterAll: 'Todas',
  filterReviewsOnly: 'Só revisões',
  emptyTitle: 'Seu mapa aparece quando você anota',
  emptyBody:
    'Crie notas na biblioteca — elas se organizam aqui por área e pasta automaticamente.',
  emptyCta: 'Ir para a biblioteca',
  summaryNotes: (n: number) => `${n} nota${n === 1 ? '' : 's'}`,
  summaryLinks: (n: number) => `${n} vínculo${n === 1 ? '' : 's'}`,
  summaryReviews: (n: number) => (n === 1 ? '1 revisão' : `${n} revisões`),
  unfiledFolder: 'Sem pasta',
  connections: (n: number) => (n === 1 ? '1 vínculo' : `${n} vínculos`),
  expandAll: 'Expandir tudo',
  collapseAll: 'Recolher',
  tapNote: 'Toque numa nota',
  sheetTitle: 'Nota',
  related: 'Conectada com',
  openNote: 'Abrir nota',
  close: 'Fechar',
  reviewOk: 'Em dia',
  reviewSoon: 'Revisar em breve',
  reviewOverdue: 'Atrasada',
  noRelated: 'Sem vínculos com outras notas ainda.',
} as const
